<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Level 1 of the chart of accounts — the equivalent of a SAP Account Group or
 * a Tally Group.
 *
 * `code` is 3 digits: the account type's digit followed by a 2-digit sequence
 * within that type (Assets => 101, 102, …). It is generated by the backend
 * inside a locked transaction and is immutable once assigned, exactly like
 * inv_purchase_requests.reference_no. Never accept it from user input.
 *
 * The UNIQUE on `code` is intentionally a plain unique rather than one scoped
 * to deleted_at: codes are allocated from MAX(code) and are never reused, so a
 * soft-deleted category can never collide with a new one.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('fin_account_categories', function (Blueprint $table): void {
            $table->id();

            // AccountType enum value: asset|liability|equity|income|expense
            $table->string('account_type', 20)->index();

            $table->string('code', 3)->unique();
            $table->string('category_name', 100);
            $table->text('description')->nullable();
            $table->boolean('is_active')->default(true);

            $table->timestamps();
            $table->softDeletes();

            // Two categories under the same type may not share a name. Scoped
            // to the type so "Current Assets" and a hypothetical "Current" row
            // under Liabilities do not clash.
            $table->index(['account_type', 'category_name']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('fin_account_categories');
    }
};
