<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<title>Available Stock Report</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'DejaVu Sans', Arial, sans-serif; font-size: 8.5pt; color: #1e293b; background: #fff; }

  /* ── Page layout ── */
  .page { padding: 20px 24px 14px; }

  /* ── Header ── */
  .header { width: 100%; margin-bottom: 10px; }
  .header table { width: 100%; }
  .company-name { font-size: 12pt; font-weight: 700; color: #111827; }
  .company-sub  { font-size: 7.5pt; color: #475569; margin-top: 1px; line-height: 1.4; }
  .doc-title    { font-size: 15pt; font-weight: 700; color: #111827; text-align: right; letter-spacing: 0.2px; white-space: nowrap; }
  .doc-sub      { font-size: 7.5pt; color: #475569; text-align: right; margin-top: 2px; }

  /* ── Info grid ── */
  .info-table { width: 100%; border-collapse: collapse; border-top: 1px solid #cbd5e1; border-bottom: 1px solid #cbd5e1; margin-bottom: 10px; }
  .info-table td { font-size: 7.8pt; padding: 3px 4px; vertical-align: top; }
  .info-label { color: #475569; white-space: nowrap; }
  .info-value { font-weight: 700; color: #111827; }

  /* ── Items table ── */
  .items-table { width: 100%; border-collapse: collapse; }
  .items-table th { background: #e2e8f0; color: #111827; font-size: 7.3pt; font-weight: 700; text-transform: uppercase; letter-spacing: 0.3px; padding: 5px 4px; border-bottom: 1px solid #cbd5e1; text-align: left; }
  .items-table td { font-size: 8pt; padding: 4px; border-bottom: 1px solid #f1f5f9; vertical-align: top; color: #1e293b; }
  .items-table tfoot td { border-top: 2px solid #94a3b8; border-bottom: none; font-weight: 700; padding-top: 6px; font-size: 8.5pt; }
  .muted { color: #94a3b8; }
  .ta-r  { text-align: right; }
  .bold  { font-weight: 700; }
  /* Colour and Available Qty stay on their own single line. A wrapped "AVAILABLE
     QTY" heading, or a quantity split from its unit, costs a whole extra row of
     height per line and reads as two values instead of one. Only Product is left
     free to wrap — it is the one column with genuinely long text. */
  .nowrap { white-space: nowrap; }

  /* ── Footer ── */
  .footer { border-top: 1px solid #e2e8f0; margin-top: 16px; padding-top: 8px; font-size: 6.8pt; color: #94a3b8; text-align: center; }
</style>
</head>
<body>
<div class="page">

  @php
    // Quantities keep their own formatter — they are not money and must not carry a currency.
    $qty       = fn ($n) => number_format((float) $n, 2);
    $money     = fn ($n) => \Modules\Inventory\Support\Money::number((float) $n);
    $cur       = \Modules\Inventory\Support\Money::code();
    $withPrice = (bool) $header['include_selling_price'];
    $cols      = $withPrice ? 5 : 4;
  @endphp

  {{-- ══ HEADER ══════════════════════════════════════════════ --}}
  <div class="header">
    <table>
      <tr>
        <td style="width:55%; vertical-align:top;">
          @if($header['company_name'])
          <div class="company-name">{{ $header['company_name'] }}</div>
          @if($header['company_address'])
          <div class="company-sub">{{ $header['company_address'] }}</div>
          @endif
          @if($header['company_email'])
          <div class="company-sub">{{ $header['company_email'] }}</div>
          @endif
          @endif
        </td>
        <td style="width:45%; vertical-align:top;">
          <div class="doc-title">AVAILABLE STOCK REPORT</div>
          <div class="doc-sub">Balance as at {{ $header['generated_at'] }}</div>
        </td>
      </tr>
    </table>
  </div>

  {{-- ══ INFO GRID ═══════════════════════════════════════════ --}}
  <table class="info-table">
    <tr>
      <td class="info-label">Location :</td>
      <td class="info-value">{{ $header['location_name'] ?? 'All' }}</td>
      <td class="info-label">Category :</td>
      <td class="info-value">{{ $header['category_name'] ?? 'All' }}</td>
      <td class="info-label">Generated By :</td>
      <td class="info-value">{{ $header['generated_by'] }}</td>
    </tr>
    <tr>
      <td class="info-label">Product :</td>
      <td class="info-value">{{ $header['product_name'] ?? 'All' }}</td>
      <td class="info-label">Colour :</td>
      <td class="info-value">{{ $header['attribute_name'] ?? 'All' }}</td>
      <td class="info-label">Generated Time :</td>
      <td class="info-value">{{ $header['generated_at'] }}</td>
    </tr>
  </table>

  {{-- ══ ITEMS TABLE ═════════════════════════════════════════ --}}
  <table class="items-table">
    <thead>
      <tr>
        <th style="width:26px;">#</th>
        <th>Product</th>
        <th class="nowrap" style="width:105px;">Colour</th>
        <th class="ta-r nowrap" style="width:110px;">Available Qty</th>
        @if($withPrice)
        <th class="ta-r nowrap" style="width:100px;">Selling Price ({{ $cur }})</th>
        @endif
      </tr>
    </thead>
    <tbody>
      @forelse($rows as $i => $row)
      <tr>
        <td class="muted">{{ $i + 1 }}</td>
        <td>{{ $row['product_name'] }}</td>
        <td class="nowrap">{{ $row['attribute_name'] ?? '—' }}</td>
        <td class="ta-r bold nowrap">{{ $qty($row['available_qty']) }} <span class="muted">{{ $row['unit'] ?? '' }}</span></td>
        @if($withPrice)
        {{-- A dash, not 0.00 — this product+colour has neither a confirmed costing nor a price list. --}}
        <td class="ta-r nowrap">{{ $row['selling_price'] === null ? '—' : $money($row['selling_price']) }}</td>
        @endif
      </tr>
      @empty
      <tr>
        <td colspan="{{ $cols }}" class="muted" style="text-align:center; padding:14px;">No available stock found for the selected filters.</td>
      </tr>
      @endforelse
    </tbody>
    @if(count($rows))
    <tfoot>
      <tr>
        {{-- Quantities are NOT summed: a category mixes Kg, m and Yards, so one total
             would add numbers that mean different things. The line count is the honest total. --}}
        <td colspan="{{ $cols }}" class="ta-r">{{ number_format($header['row_count']) }} item(s) in stock</td>
      </tr>
    </tfoot>
    @endif
  </table>

  {{-- ══ FOOTER ══════════════════════════════════════════════ --}}
  <div class="footer">
    Generated by {{ $header['generated_by'] }} on {{ $header['generated_at'] }}
  </div>

</div>
</body>
</html>
