<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<title>Outstanding Summary</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'DejaVu Sans', Arial, sans-serif; font-size: 8.5pt; color: #1e293b; background: #fff; }

  /* ── Page layout ── */
  .page { padding: 20px 24px 14px; }

  /* ── Header ── */
  .header { width: 100%; margin-bottom: 10px; }
  .header table { width: 100%; }
  .company-name { font-size: 12pt; font-weight: 700; color: #111827; }
  .company-sub  { font-size: 7.5pt; color: #475569; margin-top: 1px; line-height: 1.4; }
  .doc-title    { font-size: 15pt; font-weight: 700; color: #111827; text-align: right; letter-spacing: 0.2px; white-space: nowrap; }
  .doc-sub      { font-size: 7.5pt; color: #475569; text-align: right; margin-top: 2px; }

  /* ── Info grid ── */
  .info-table { width: 100%; border-collapse: collapse; border-top: 1px solid #cbd5e1; border-bottom: 1px solid #cbd5e1; margin-bottom: 10px; }
  .info-table td { font-size: 7.8pt; padding: 3px 4px; vertical-align: top; }
  .info-label { color: #475569; white-space: nowrap; }
  .info-value { font-weight: 700; color: #111827; }

  /* ── Items table ── */
  .items-table { width: 100%; border-collapse: collapse; }
  .items-table th { background: #e2e8f0; color: #111827; font-size: 7.3pt; font-weight: 700; text-transform: uppercase; letter-spacing: 0.3px; padding: 5px 4px; border-bottom: 1px solid #cbd5e1; text-align: left; }
  .items-table td { font-size: 8pt; padding: 4px; border-bottom: 1px solid #f1f5f9; vertical-align: top; color: #1e293b; }
  .cust-row td { background: #f8fafc; font-weight: 700; font-size: 8.5pt; padding: 6px 4px 4px; border-bottom: 1px solid #e2e8f0; border-top: 1px solid #e2e8f0; }
  .cust-total-row td { font-weight: 700; padding-top: 4px; border-bottom: 1px solid #cbd5e1; }
  .items-table tfoot td { border-top: 2px solid #94a3b8; border-bottom: none; font-weight: 700; padding-top: 6px; font-size: 9pt; }
  .overdue { color: #dc2626; font-weight: 700; }
  .muted { color: #94a3b8; }
  .ta-r  { text-align: right; }

  /* ── Footer ── */
  .footer { border-top: 1px solid #e2e8f0; margin-top: 16px; padding-top: 8px; font-size: 6.8pt; color: #94a3b8; text-align: center; }
</style>
</head>
<body>
<div class="page">

  @php
    $fmt   = fn ($n) => number_format((float) $n, 2);
    $money = fn ($n) => \Modules\Inventory\Support\Money::number((float) $n);
    $cur   = \Modules\Inventory\Support\Money::code();
  @endphp

  {{-- ══ HEADER ══════════════════════════════════════════════ --}}
  <div class="header">
    <table>
      <tr>
        <td style="width:55%; vertical-align:top;">
          @if($header['company_name'])
          <div class="company-name">{{ $header['company_name'] }}</div>
          @if($header['company_address'])
          <div class="company-sub">{{ $header['company_address'] }}</div>
          @endif
          @if($header['company_email'])
          <div class="company-sub">{{ $header['company_email'] }}</div>
          @endif
          @endif
        </td>
        <td style="width:45%; vertical-align:top;">
          <div class="doc-title">OUTSTANDING SUMMARY</div>
          <div class="doc-sub">As Of: {{ $header['as_of'] }}</div>
        </td>
      </tr>
    </table>
  </div>

  {{-- ══ INFO GRID ═══════════════════════════════════════════ --}}
  <table class="info-table">
    <tr>
      <td class="info-label">Customer :</td>
      <td class="info-value">{{ $header['customer_name'] ?? 'All' }}</td>
      <td class="info-label">Overdue Only :</td>
      <td class="info-value">{{ $header['overdue_only'] ? 'Yes' : 'No' }}</td>
      <td class="info-label">Generated By :</td>
      <td class="info-value">{{ $header['generated_by'] }}</td>
    </tr>
    <tr>
      <td class="info-label">Invoices :</td>
      <td class="info-value">{{ $header['total_invoices'] }}</td>
      <td class="info-label">Total Outstanding :</td>
      <td class="info-value">{{ \Modules\Inventory\Support\Money::format((float) $header['total_outstanding']) }}</td>
      <td class="info-label">Generated Time :</td>
      <td class="info-value">{{ $header['generated_at'] }}</td>
    </tr>
  </table>

  {{-- ══ ITEMS TABLE ═════════════════════════════════════════ --}}
  <table class="items-table">
    <thead>
      <tr>
        <th>Invoice No</th>
        <th style="width:60px;">Date</th>
        <th style="width:60px;">Due Date</th>
        <th class="ta-r" style="width:50px;">Days O/D</th>
        <th style="width:70px;">SO No</th>
        <th style="width:70px;">DO No</th>
        <th class="ta-r" style="width:75px;">Amount</th>
        <th class="ta-r" style="width:75px;">Received</th>
        <th class="ta-r" style="width:80px;">Outstanding ({{ $cur }})</th>
      </tr>
    </thead>
    <tbody>
      @forelse($customers as $customer)
      <tr class="cust-row">
        <td colspan="9">{{ $customer['customer_name'] }}</td>
      </tr>
      @foreach($customer['invoices'] as $inv)
      <tr>
        <td>{{ $inv['invoice_no'] }}</td>
        <td>{{ $inv['invoice_date'] }}</td>
        <td>{{ $inv['due_date'] ?? '—' }}</td>
        <td class="ta-r {{ ($inv['days_overdue'] ?? 0) > 0 ? 'overdue' : '' }}">{{ $inv['days_overdue'] ?? '—' }}</td>
        <td>{{ $inv['so_no'] ?? '—' }}</td>
        <td>{{ $inv['do_no'] ?? '—' }}</td>
        <td class="ta-r">{{ $money($inv['amount']) }}</td>
        <td class="ta-r">{{ $money($inv['received']) }}</td>
        <td class="ta-r">{{ $money($inv['outstanding']) }}</td>
      </tr>
      @endforeach
      <tr class="cust-total-row">
        <td colspan="8" class="ta-r">Total {{ $customer['customer_name'] }}</td>
        <td class="ta-r">{{ $money($customer['customer_outstanding']) }}</td>
      </tr>
      @empty
      <tr>
        <td colspan="9" class="muted" style="text-align:center; padding:14px;">No outstanding invoices found.</td>
      </tr>
      @endforelse
    </tbody>
    @if(count($customers))
    <tfoot>
      <tr>
        <td colspan="8" class="ta-r">Grand Total</td>
        <td class="ta-r">{{ $money($summary['total_outstanding']) }}</td>
      </tr>
    </tfoot>
    @endif
  </table>

  {{-- ══ FOOTER ══════════════════════════════════════════════ --}}
  <div class="footer">
    Generated by {{ $header['generated_by'] }} on {{ $header['generated_at'] }}
  </div>

</div>
</body>
</html>
