<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<title>Sales Summary</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'DejaVu Sans', Arial, sans-serif; font-size: 8.5pt; color: #1e293b; background: #fff; }

  /* ── Page layout ── */
  .page { padding: 20px 24px 14px; }

  /* ── Header ── */
  .header { width: 100%; margin-bottom: 10px; }
  .header table { width: 100%; }
  .company-name { font-size: 12pt; font-weight: 700; color: #111827; }
  .company-sub  { font-size: 7.5pt; color: #475569; margin-top: 1px; line-height: 1.4; }
  .doc-title    { font-size: 15pt; font-weight: 700; color: #111827; text-align: right; letter-spacing: 0.2px; white-space: nowrap; }
  .doc-sub      { font-size: 7.5pt; color: #475569; text-align: right; margin-top: 2px; }

  /* ── Info grid ── */
  .info-table { width: 100%; border-collapse: collapse; border-top: 1px solid #cbd5e1; border-bottom: 1px solid #cbd5e1; margin-bottom: 10px; }
  .info-table td { font-size: 7.8pt; padding: 3px 4px; vertical-align: top; }
  .info-label { color: #475569; white-space: nowrap; }
  .info-value { font-weight: 700; color: #111827; }

  /* ── Items table ── */
  .items-table { width: 100%; border-collapse: collapse; }
  .items-table th { background: #e2e8f0; color: #111827; font-size: 7.3pt; font-weight: 700; text-transform: uppercase; letter-spacing: 0.3px; padding: 5px 4px; border-bottom: 1px solid #cbd5e1; text-align: left; }
  .items-table td { font-size: 8pt; padding: 4px; border-bottom: 1px solid #f1f5f9; vertical-align: top; color: #1e293b; }
  .items-table tfoot td { border-top: 2px solid #94a3b8; border-bottom: none; font-weight: 700; padding-top: 6px; font-size: 9pt; }
  .bold  { font-weight: 700; }
  .muted { color: #94a3b8; }
  .ta-r  { text-align: right; }

  /* ── Footer ── */
  .footer { border-top: 1px solid #e2e8f0; margin-top: 16px; padding-top: 8px; font-size: 6.8pt; color: #94a3b8; text-align: center; }
</style>
</head>
<body>
<div class="page">

  @php
    $money = fn ($n) => \Modules\Inventory\Support\Money::number((float) $n);
    $cur   = \Modules\Inventory\Support\Money::code();
  @endphp

  {{-- ══ HEADER ══════════════════════════════════════════════ --}}
  <div class="header">
    <table>
      <tr>
        <td style="width:55%; vertical-align:top;">
          @if($header['company_name'])
          <div class="company-name">{{ $header['company_name'] }}</div>
          @if($header['company_address'])
          <div class="company-sub">{{ $header['company_address'] }}</div>
          @endif
          @if($header['company_email'])
          <div class="company-sub">{{ $header['company_email'] }}</div>
          @endif
          @endif
        </td>
        <td style="width:45%; vertical-align:top;">
          <div class="doc-title">SALES SUMMARY</div>
          <div class="doc-sub">
            Period: {{ $header['date_from'] ?? 'Beginning' }} — {{ $header['date_to'] ?? 'To Date' }}
          </div>
        </td>
      </tr>
    </table>
  </div>

  {{-- ══ INFO GRID ═══════════════════════════════════════════ --}}
  <table class="info-table">
    <tr>
      <td class="info-label">Number of Bills :</td>
      <td class="info-value">{{ $header['bill_count'] }}</td>
      <td class="info-label">Net Sale :</td>
      <td class="info-value">{{ \Modules\Inventory\Support\Money::format((float) $header['net_sale']) }}</td>
      <td class="info-label">Generated By :</td>
      <td class="info-value">{{ $header['generated_by'] }}</td>
    </tr>
    <tr>
      <td class="info-label">Cash Sale :</td>
      <td class="info-value">{{ \Modules\Inventory\Support\Money::format((float) $header['cash_sale']) }}</td>
      <td class="info-label">Non Cash Sale :</td>
      <td class="info-value">{{ \Modules\Inventory\Support\Money::format((float) $header['non_cash_sale']) }}</td>
      <td class="info-label">Generated Time :</td>
      <td class="info-value">{{ $header['generated_at'] }}</td>
    </tr>
  </table>

  {{-- ══ DATE-WISE TABLE ═════════════════════════════════════ --}}
  <table class="items-table">
    <thead>
      <tr>
        <th>Date</th>
        <th class="ta-r">Cash</th>
        <th class="ta-r">Credit</th>
        <th class="ta-r">Cheque</th>
        <th class="ta-r">Bank Deposit</th>
        <th class="ta-r">Cards</th>
        <th class="ta-r">Total Sales</th>
      </tr>
    </thead>
    <tbody>
      @forelse($rows as $row)
      <tr>
        <td>{{ $row['date'] }}</td>
        <td class="ta-r">{{ $money($row['cash']) }}</td>
        <td class="ta-r">{{ $money($row['credit']) }}</td>
        <td class="ta-r">{{ $money($row['cheque']) }}</td>
        <td class="ta-r">{{ $money($row['bank_deposit']) }}</td>
        <td class="ta-r">{{ $money($row['cards']) }}</td>
        <td class="ta-r bold">{{ $money($row['total_sales']) }}</td>
      </tr>
      @empty
      <tr>
        <td colspan="7" class="muted" style="text-align:center; padding:14px;">No sales found for the selected period.</td>
      </tr>
      @endforelse
    </tbody>
    @if(count($rows))
    <tfoot>
      <tr>
        <td>Total ({{ $cur }})</td>
        <td class="ta-r">{{ $money($summary['cash']) }}</td>
        <td class="ta-r">{{ $money($summary['credit']) }}</td>
        <td class="ta-r">{{ $money($summary['cheque']) }}</td>
        <td class="ta-r">{{ $money($summary['bank_deposit']) }}</td>
        <td class="ta-r">{{ $money($summary['cards']) }}</td>
        <td class="ta-r">{{ $money($summary['total_sales']) }}</td>
      </tr>
    </tfoot>
    @endif
  </table>

  {{-- ══ FOOTER ══════════════════════════════════════════════ --}}
  <div class="footer">
    Generated by {{ $header['generated_by'] }} on {{ $header['generated_at'] }}
  </div>

</div>
</body>
</html>
