<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<title>Stock Movement Summary</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'DejaVu Sans', Arial, sans-serif; font-size: 8.5pt; color: #1e293b; background: #fff; }

  /* ── Page layout ── */
  .page { padding: 20px 24px 14px; }

  /* ── Header ── */
  .header { width: 100%; margin-bottom: 10px; }
  .header table { width: 100%; }
  .company-name { font-size: 12pt; font-weight: 700; color: #111827; }
  .company-sub  { font-size: 7.5pt; color: #475569; margin-top: 1px; line-height: 1.4; }
  .doc-title    { font-size: 15pt; font-weight: 700; color: #111827; text-align: right; letter-spacing: 0.2px; white-space: nowrap; }
  .doc-sub      { font-size: 7.5pt; color: #475569; text-align: right; margin-top: 2px; }

  /* ── Info grid ── */
  .info-table { width: 100%; border-collapse: collapse; border-top: 1px solid #cbd5e1; border-bottom: 1px solid #cbd5e1; margin-bottom: 10px; }
  .info-table td { font-size: 7.8pt; padding: 3px 4px; vertical-align: top; }
  .info-label { color: #475569; white-space: nowrap; }
  .info-value { font-weight: 700; color: #111827; }

  /* ── Items table ── */
  .items-table { width: 100%; border-collapse: collapse; }
  .items-table th { background: #e2e8f0; color: #111827; font-size: 7.3pt; font-weight: 700; text-transform: uppercase; letter-spacing: 0.3px; padding: 5px 4px; border-bottom: 1px solid #cbd5e1; text-align: left; }
  .items-table th.group { text-align: center; border-left: 1px solid #cbd5e1; }
  .items-table th.sub   { text-align: right; background: #f1f5f9; }
  .items-table th.sub-first { border-left: 1px solid #cbd5e1; }
  .items-table td { font-size: 8pt; padding: 4px; border-bottom: 1px solid #f1f5f9; vertical-align: top; color: #1e293b; }
  .items-table tfoot td { border-top: 1px solid #cbd5e1; border-bottom: none; font-weight: 700; padding-top: 5px; }
  .mono  { font-family: 'DejaVu Sans Mono', monospace; font-size: 7.5pt; color: #475569; }
  .bold  { font-weight: 700; }
  .muted { color: #94a3b8; }
  .ta-r  { text-align: right; }
  .sep   { border-left: 1px solid #f1f5f9; }

  /* ── Footer ── */
  .footer { border-top: 1px solid #e2e8f0; margin-top: 16px; padding-top: 8px; font-size: 6.8pt; color: #94a3b8; text-align: center; }
</style>
</head>
<body>
<div class="page">

  @php
    // Quantities stay bare; only the money columns carry a currency.
    $fmt   = fn ($n) => number_format((float) $n, 2);
    $money = fn ($n) => \Modules\Inventory\Support\Money::number((float) $n);
    $cur   = \Modules\Inventory\Support\Money::code();
  @endphp

  {{-- ══ HEADER ══════════════════════════════════════════════ --}}
  <div class="header">
    <table>
      <tr>
        <td style="width:55%; vertical-align:top;">
          @if($header['company_name'])
          <div class="company-name">{{ $header['company_name'] }}</div>
          @if($header['company_address'])
          <div class="company-sub">{{ $header['company_address'] }}</div>
          @endif
          @if($header['company_email'])
          <div class="company-sub">{{ $header['company_email'] }}</div>
          @endif
          @endif
        </td>
        <td style="width:45%; vertical-align:top;">
          <div class="doc-title">STOCK MOVEMENT SUMMARY</div>
          <div class="doc-sub">
            Period: {{ $header['date_from'] ?? 'Beginning' }} — {{ $header['date_to'] ?? 'To Date' }}
          </div>
        </td>
      </tr>
    </table>
  </div>

  {{-- ══ INFO GRID ═══════════════════════════════════════════ --}}
  <table class="info-table">
    <tr>
      <td class="info-label">Opening Qty :</td>
      <td class="info-value">{{ $fmt($header['opening_qty']) }}</td>
      <td class="info-label">Closing Qty :</td>
      <td class="info-value">{{ $fmt($header['closing_qty']) }}</td>
      <td class="info-label">Location :</td>
      <td class="info-value">{{ $header['location_name'] ?? 'All' }}</td>
      <td class="info-label">Generated By :</td>
      <td class="info-value">{{ $header['generated_by'] }}</td>
    </tr>
    <tr>
      <td class="info-label">Opening Value :</td>
      <td class="info-value">{{ \Modules\Inventory\Support\Money::format((float) $header['opening_value']) }}</td>
      <td class="info-label">Closing Value :</td>
      <td class="info-value">{{ \Modules\Inventory\Support\Money::format((float) $header['closing_value']) }}</td>
      <td class="info-label">Warehouse :</td>
      <td class="info-value">{{ $header['store_name'] ?? 'All' }}</td>
      <td class="info-label">Generated Time :</td>
      <td class="info-value">{{ $header['generated_at'] }}</td>
    </tr>
    <tr>
      <td class="info-label">Category :</td>
      <td class="info-value" colspan="7">{{ $header['category_name'] ?? 'All' }}</td>
    </tr>
  </table>

  {{-- ══ SUMMARY TABLE ═══════════════════════════════════════ --}}
  <table class="items-table">
    <thead>
      <tr>
        <th rowspan="2" style="width:24px;">#</th>
        <th rowspan="2">Item Description</th>
        <th rowspan="2" style="width:60px;">Unit</th>
        <th colspan="2" class="group">Opening Balance</th>
        <th colspan="2" class="group">Purchase</th>
        <th colspan="2" class="group">Sales / Consumptions</th>
        <th colspan="2" class="group">Closing Balance</th>
      </tr>
      <tr>
        <th class="sub sub-first" style="width:58px;">Qty</th>
        <th class="sub" style="width:70px;">Value ({{ $cur }})</th>
        <th class="sub sub-first" style="width:58px;">Qty</th>
        <th class="sub" style="width:70px;">Value ({{ $cur }})</th>
        <th class="sub sub-first" style="width:58px;">Qty</th>
        <th class="sub" style="width:70px;">Value ({{ $cur }})</th>
        <th class="sub sub-first" style="width:58px;">Qty</th>
        <th class="sub" style="width:70px;">Value ({{ $cur }})</th>
      </tr>
    </thead>
    <tbody>
      @forelse($rows as $i => $row)
      <tr>
        <td class="muted">{{ $i + 1 }}</td>
        <td>{{ $row['product_name'] }}</td>
        <td>{{ $row['unit'] ?? '—' }}</td>
        <td class="ta-r sep">{{ $fmt($row['opening_qty']) }}</td>
        <td class="ta-r">{{ $money($row['opening_value']) }}</td>
        <td class="ta-r sep">{{ $fmt($row['purchase_qty']) }}</td>
        <td class="ta-r">{{ $money($row['purchase_value']) }}</td>
        <td class="ta-r sep">{{ $fmt($row['sales_qty']) }}</td>
        <td class="ta-r">{{ $money($row['sales_value']) }}</td>
        <td class="ta-r sep bold">{{ $fmt($row['closing_qty']) }}</td>
        <td class="ta-r bold">{{ $money($row['closing_value']) }}</td>
      </tr>
      @empty
      <tr>
        <td colspan="11" class="muted" style="text-align:center; padding:14px;">No stock movement found for the selected filters.</td>
      </tr>
      @endforelse
    </tbody>
    <tfoot>
      <tr>
        <td colspan="3" class="ta-r">Total</td>
        <td class="ta-r"></td>
        <td class="ta-r">{{ $money($summary['opening_value']) }}</td>
        <td class="ta-r"></td>
        <td class="ta-r">{{ $money($summary['purchase_value']) }}</td>
        <td class="ta-r"></td>
        <td class="ta-r">{{ $money($summary['sales_value']) }}</td>
        <td class="ta-r"></td>
        <td class="ta-r">{{ $money($summary['closing_value']) }}</td>
      </tr>
    </tfoot>
  </table>

  {{-- ══ FOOTER ══════════════════════════════════════════════ --}}
  <div class="footer">
    Generated by {{ $header['generated_by'] }} on {{ $header['generated_at'] }}
  </div>

</div>
</body>
</html>
