<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<title>Supplier Wise GRN Details</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'DejaVu Sans', Arial, sans-serif; font-size: 8.5pt; color: #1e293b; background: #fff; }

  /* ── Page layout ── */
  .page { padding: 20px 24px 14px; }

  /* ── Header ── */
  .header { width: 100%; margin-bottom: 10px; }
  .header table { width: 100%; }
  .company-name { font-size: 12pt; font-weight: 700; color: #111827; }
  .company-sub  { font-size: 7.5pt; color: #475569; margin-top: 1px; line-height: 1.4; }
  .doc-title    { font-size: 15pt; font-weight: 700; color: #111827; text-align: right; letter-spacing: 0.2px; white-space: nowrap; }
  .doc-sub      { font-size: 7.5pt; color: #475569; text-align: right; margin-top: 2px; }

  /* ── Info grid ── */
  .info-table { width: 100%; border-collapse: collapse; border-top: 1px solid #cbd5e1; border-bottom: 1px solid #cbd5e1; margin-bottom: 10px; }
  .info-table td { font-size: 7.8pt; padding: 3px 4px; vertical-align: top; }
  .info-label { color: #475569; white-space: nowrap; }
  .info-value { font-weight: 700; color: #111827; }

  /* ── Items table ── */
  .items-table { width: 100%; border-collapse: collapse; }
  .items-table th { background: #e2e8f0; color: #111827; font-size: 7.3pt; font-weight: 700; text-transform: uppercase; letter-spacing: 0.3px; padding: 5px 4px; border-bottom: 1px solid #cbd5e1; text-align: left; }
  .items-table td { font-size: 8pt; padding: 4px; border-bottom: 1px solid #f1f5f9; vertical-align: top; color: #1e293b; }
  .supplier-row td { background: #f8fafc; font-weight: 700; font-size: 8.5pt; padding: 6px 4px 4px; border-bottom: 1px solid #e2e8f0; border-top: 1px solid #e2e8f0; }
  .grn-info-row td { background: #fcfcfd; font-weight: 700; font-size: 7.5pt; color: #475569; padding: 5px 4px; border-bottom: 1px solid #f1f5f9; }
  .grn-total-row td { font-weight: 700; padding-top: 4px; border-bottom: 1px solid #e2e8f0; }
  .supplier-total-row td { font-weight: 700; padding-top: 4px; border-bottom: 1px solid #cbd5e1; }
  .items-table tfoot td { border-top: 2px solid #94a3b8; border-bottom: none; font-weight: 700; padding-top: 6px; font-size: 9pt; }
  .muted { color: #94a3b8; }
  .ta-r  { text-align: right; }

  /* ── Footer ── */
  .footer { border-top: 1px solid #e2e8f0; margin-top: 16px; padding-top: 8px; font-size: 6.8pt; color: #94a3b8; text-align: center; }
</style>
</head>
<body>
<div class="page">

  @php
    $fmt   = fn ($n) => number_format((float) $n, 2);
    $money = fn ($n) => \Modules\Inventory\Support\Money::number((float) $n);
    $cur   = \Modules\Inventory\Support\Money::code();
  @endphp

  {{-- ══ HEADER ══════════════════════════════════════════════ --}}
  <div class="header">
    <table>
      <tr>
        <td style="width:55%; vertical-align:top;">
          @if($header['company_name'])
          <div class="company-name">{{ $header['company_name'] }}</div>
          @if($header['company_address'])
          <div class="company-sub">{{ $header['company_address'] }}</div>
          @endif
          @if($header['company_email'])
          <div class="company-sub">{{ $header['company_email'] }}</div>
          @endif
          @endif
        </td>
        <td style="width:45%; vertical-align:top;">
          <div class="doc-title">SUPPLIER WISE GRN DETAILS</div>
          <div class="doc-sub">
            Period: {{ $header['date_from'] }} — {{ $header['date_to'] }}
          </div>
        </td>
      </tr>
    </table>
  </div>

  {{-- ══ INFO GRID ═══════════════════════════════════════════ --}}
  <table class="info-table">
    <tr>
      <td class="info-label">Supplier :</td>
      <td class="info-value">{{ $header['supplier_name'] ?? 'All' }}</td>
      <td class="info-label">Item :</td>
      <td class="info-value">{{ $header['product_name'] ?? 'All' }}</td>
      <td class="info-label">Generated By :</td>
      <td class="info-value">{{ $header['generated_by'] }}</td>
    </tr>
    <tr>
      <td class="info-label">Total Qty :</td>
      <td class="info-value">{{ $fmt($header['total_qty']) }}</td>
      <td class="info-label">Total Amount :</td>
      <td class="info-value">{{ \Modules\Inventory\Support\Money::format((float) $header['total_amount']) }}</td>
      <td class="info-label">Generated Time :</td>
      <td class="info-value">{{ $header['generated_at'] }}</td>
    </tr>
  </table>

  {{-- ══ ITEMS TABLE ═════════════════════════════════════════ --}}
  <table class="items-table">
    <thead>
      <tr>
        <th style="width:70px;">Item Code</th>
        <th>Item Name</th>
        <th class="ta-r" style="width:60px;">Qty</th>
        <th style="width:55px;">UOM</th>
        <th class="ta-r" style="width:65px;">Unit Price</th>
        <th class="ta-r" style="width:55px;">Discount</th>
        <th class="ta-r" style="width:50px;">Tax</th>
        <th class="ta-r" style="width:85px;">Amount ({{ $cur }})</th>
      </tr>
    </thead>
    <tbody>
      @forelse($suppliers as $supplier)
      <tr class="supplier-row">
        <td colspan="8">{{ $supplier['supplier_name'] }}</td>
      </tr>
      @foreach($supplier['grns'] as $grn)
      <tr class="grn-info-row">
        <td colspan="2">GRN No: {{ $grn['grn_no'] }}</td>
        <td colspan="2">GRN Date: {{ $grn['grn_date'] }}</td>
        <td colspan="2">PO No: {{ $grn['po_no'] ?? '—' }}</td>
        <td colspan="2" class="ta-r">Total Qty: {{ $fmt($grn['total_qty']) }}</td>
      </tr>
      @foreach($grn['items'] as $item)
      <tr>
        <td>{{ $item['product_code'] }}</td>
        <td>{{ $item['item_name'] }}</td>
        <td class="ta-r">{{ $fmt($item['quantity']) }}</td>
        <td>{{ $item['unit'] ?? '—' }}</td>
        <td class="ta-r">{{ $money($item['unit_price']) }}</td>
        <td class="ta-r">{{ $fmt($item['discount']) }}%</td>
        <td class="ta-r">{{ $fmt($item['tax']) }}%</td>
        <td class="ta-r">{{ $money($item['amount']) }}</td>
      </tr>
      @endforeach
      <tr class="grn-total-row">
        <td colspan="7" class="ta-r">TOTAL</td>
        <td class="ta-r">{{ $money($grn['grn_amount']) }}</td>
      </tr>
      @endforeach
      <tr class="supplier-total-row">
        <td colspan="7" class="ta-r">Total {{ $supplier['supplier_name'] }}</td>
        <td class="ta-r">{{ $money($supplier['supplier_amount']) }}</td>
      </tr>
      @empty
      <tr>
        <td colspan="8" class="muted" style="text-align:center; padding:14px;">No GRNs found for the selected filters.</td>
      </tr>
      @endforelse
    </tbody>
    @if(count($suppliers))
    <tfoot>
      <tr>
        <td colspan="7" class="ta-r">Grand Total</td>
        <td class="ta-r">{{ $money($summary['total_amount']) }}</td>
      </tr>
    </tfoot>
    @endif
  </table>

  {{-- ══ FOOTER ══════════════════════════════════════════════ --}}
  <div class="footer">
    Generated by {{ $header['generated_by'] }} on {{ $header['generated_at'] }}
  </div>

</div>
</body>
</html>
