-- MySQL Script generated by MySQL Workbench
-- Thu Jun 11 17:48:41 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema inv_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `inv_db` ;

-- -----------------------------------------------------
-- Schema inv_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inv_db` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------

USE `inv_db` ;

-- -----------------------------------------------------
-- Table `inv_db`.`industry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inv_db`.`industry` ;

CREATE TABLE IF NOT EXISTS `inv_db`.`industry` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inv_db`.`Company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inv_db`.`Company` ;

CREATE TABLE IF NOT EXISTS `inv_db`.`Company` (
  `id` INT NOT NULL,
  `company_type` VARCHAR(45) NULL,
  `company_name` VARCHAR(45) NULL,
  `registration_no` VARCHAR(45) NULL,
  `tax_reg_no` VARCHAR(45) NULL,
  `street_address` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `postal_zip_code` VARCHAR(45) NULL,
  `company_email` VARCHAR(45) NULL,
  `company_mobile` VARCHAR(45) NULL,
  `industry_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Company_industry1_idx` (`industry_id` ASC) VISIBLE,
  CONSTRAINT `fk_Company_industry1`
    FOREIGN KEY (`industry_id`)
    REFERENCES `inv_db`.`industry` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inv_db`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inv_db`.`location` ;

CREATE TABLE IF NOT EXISTS `inv_db`.`location` (
  `id` INT NOT NULL,
  `parent_location` VARCHAR(45) NULL,
  `location_type` VARCHAR(45) NULL,
  `location_code` VARCHAR(45) NULL,
  `location_name` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `base_currrency` VARCHAR(45) NULL,
  `Company_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_location_Company1_idx` (`Company_id` ASC) VISIBLE,
  CONSTRAINT `fk_location_Company1`
    FOREIGN KEY (`Company_id`)
    REFERENCES `inv_db`.`Company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inv_db`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inv_db`.`category` ;

CREATE TABLE IF NOT EXISTS `inv_db`.`category` (
  `id` INT NOT NULL,
  `product_service_type` VARCHAR(45) NULL,
  `industry_name` VARCHAR(45) NULL,
  `company` VARCHAR(45) NULL,
  `parent_category` VARCHAR(45) NULL,
  `category_name` VARCHAR(45) NULL,
  `reference_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inv_db`.`attribute_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inv_db`.`attribute_type` ;

CREATE TABLE IF NOT EXISTS `inv_db`.`attribute_type` (
  `id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `product_service_type` VARCHAR(45) NULL,
  `attribute_type_name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_attribute_type_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_attribute_type_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `inv_db`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inv_db`.`unit_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inv_db`.`unit_category` ;

CREATE TABLE IF NOT EXISTS `inv_db`.`unit_category` (
  `id` INT NOT NULL,
  `unit_category` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inv_db`.`unit_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inv_db`.`unit_type` ;

CREATE TABLE IF NOT EXISTS `inv_db`.`unit_type` (
  `id` INT NOT NULL,
  `idunit_category` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `unit_type_name` VARCHAR(45) NULL,
  `unit_type_symble` VARCHAR(45) NULL,
  `unit_position` VARCHAR(45) NULL,
  `unit_category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_unit_type_unit_category1_idx` (`unit_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_unit_type_unit_category1`
    FOREIGN KEY (`unit_category_id`)
    REFERENCES `inv_db`.`unit_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inv_db`.`supplier_master`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inv_db`.`supplier_master` ;

CREATE TABLE IF NOT EXISTS `inv_db`.`supplier_master` (
  `id` INT NOT NULL,
  `supplier_code` VARCHAR(45) NULL,
  `reference_no` VARCHAR(45) NULL,
  `supplier_type` VARCHAR(45) NULL,
  `supplier_name` VARCHAR(45) NULL,
  `check_writer_name` VARCHAR(45) NULL,
  `mobile` INT NULL,
  `land_line` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `fax` INT NULL,
  `bil_address_line_1` VARCHAR(45) NULL,
  `bil_address_line_2` VARCHAR(45) NULL,
  `bil_address_line_3` VARCHAR(45) NULL,
  `bil_city` VARCHAR(45) NULL,
  `bil_postal_code` VARCHAR(45) NULL,
  `bil_country` VARCHAR(45) NULL,
  `bil_state_province` VARCHAR(45) NULL,
  `tax_type` VARCHAR(45) NULL,
  `tax_no` VARCHAR(45) NULL,
  `tax_regis_no` VARCHAR(45) NULL,
  `website` VARCHAR(45) NULL,
  `credit_limit` VARCHAR(45) NULL,
  `creadit_period` VARCHAR(45) NULL,
  `previleges_discount` VARCHAR(45) NULL,
  `bank_name` VARCHAR(45) NULL,
  `bank_branch` VARCHAR(45) NULL,
  `bank_acc_holder_name` VARCHAR(45) NULL,
  `bank_acc_no` VARCHAR(45) NULL,
  `contact_person_name` VARCHAR(45) NULL,
  `contact_person_designation` VARCHAR(45) NULL,
  `contact_person_mobile` VARCHAR(45) NULL,
  `contact_person_email` VARCHAR(45) NULL,
  `contact_person_fax` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inv_db`.`customer_master`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inv_db`.`customer_master` ;

CREATE TABLE IF NOT EXISTS `inv_db`.`customer_master` (
  `id` INT NOT NULL,
  `customer_code` VARCHAR(45) NULL,
  `reference_no` VARCHAR(45) NULL,
  `customer_type` VARCHAR(45) NULL,
  `title` VARCHAR(45) NULL,
  `customer_name` VARCHAR(45) NULL,
  `nic_passport_drivingLicence` VARCHAR(45) NULL,
  `attachments` VARCHAR(45) NULL,
  `br_no` VARCHAR(45) NULL,
  `customer_mobile` VARCHAR(45) NULL,
  `customer_landLine` VARCHAR(45) NULL,
  `customer_email` VARCHAR(45) NULL,
  `customer_fax` VARCHAR(45) NULL,
  `billing_address_line1` VARCHAR(45) NULL,
  `billing_address_line2` VARCHAR(45) NULL,
  `billing_address_line3` VARCHAR(45) NULL,
  `billing_address_address_city` VARCHAR(45) NULL,
  `billing_address_zip_postal` INT NULL,
  `billing_address_state_province` VARCHAR(45) NULL,
  `billing_address_country` VARCHAR(45) NULL,
  `shipping_address_line1` VARCHAR(45) NULL,
  `shipping_address_line2` VARCHAR(45) NULL,
  `shipping_address_line3` VARCHAR(45) NULL,
  `shipping_address_address_city` VARCHAR(45) NULL,
  `shipping_address_zip_postal` VARCHAR(45) NULL,
  `shipping_address_state_province` VARCHAR(45) NULL,
  `shipping_address_country` VARCHAR(45) NULL,
  `sale_manage` VARCHAR(45) NULL,
  `sales_executive` VARCHAR(45) NULL,
  `sales_person` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inv_db`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inv_db`.`product` ;

CREATE TABLE IF NOT EXISTS `inv_db`.`product` (
  `id` INT NOT NULL,
  `product_code` VARCHAR(45) NULL,
  `reference_no` VARCHAR(45) NULL,
  `ean_13` VARCHAR(45) NULL,
  `pro_name` VARCHAR(45) NULL,
  `display_name` VARCHAR(45) NULL,
  `product_type` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `category` VARCHAR(45) NULL,
  `location` VARCHAR(45) NULL,
  `reorder_level` DECIMAL NULL,
  `reorder_qty` DECIMAL NULL,
  `reorder_period` VARCHAR(45) NULL,
  `stock_releasing_method` VARCHAR(45) NULL,
  `tracking_type` ENUM("Batch", "Serial") NULL,
  `lock_purchase` VARCHAR(45) NULL,
  `complimentary_items` VARCHAR(45) NULL,
  `free_issue` VARCHAR(45) NULL,
  `allow_minus` VARCHAR(45) NULL,
  `not_allow_direct_sale` VARCHAR(45) NULL,
  `non_returnable` VARCHAR(45) NULL,
  `is_empty` VARCHAR(45) NULL,
  `is_batch` VARCHAR(45) NULL,
  `is_serial` VARCHAR(45) NULL,
  `service_charge` VARCHAR(45) NULL,
  `loyalty` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inv_db`.`product_has_supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inv_db`.`product_has_supplier` ;

CREATE TABLE IF NOT EXISTS `inv_db`.`product_has_supplier` (
  `id` VARCHAR(45) NOT NULL,
  `supplier_master_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_has_supplier_supplier_master1_idx` (`supplier_master_id` ASC) VISIBLE,
  INDEX `fk_product_has_supplier_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_has_supplier_supplier_master1`
    FOREIGN KEY (`supplier_master_id`)
    REFERENCES `inv_db`.`supplier_master` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_supplier_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `inv_db`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inv_db`.`product_has_images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inv_db`.`product_has_images` ;

CREATE TABLE IF NOT EXISTS `inv_db`.`product_has_images` (
  `id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `url` VARCHAR(45) NULL DEFAULT 'default_product.webp',
  INDEX `fk_product_has_images_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_has_images_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `inv_db`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inv_db`.`product_has_attribute`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inv_db`.`product_has_attribute` ;

CREATE TABLE IF NOT EXISTS `inv_db`.`product_has_attribute` (
  `id` INT NOT NULL,
  `attribute_type` VARCHAR(45) NULL,
  `attribute` VARCHAR(45) NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_has_attribute_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_has_attribute_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `inv_db`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inv_db`.`product_has_location_store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inv_db`.`product_has_location_store` ;

CREATE TABLE IF NOT EXISTS `inv_db`.`product_has_location_store` (
  `id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `location` VARCHAR(45) NULL,
  `store` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_has_location_store_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_has_location_store_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `inv_db`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inv_db`.`sales_channel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inv_db`.`sales_channel` ;

CREATE TABLE IF NOT EXISTS `inv_db`.`sales_channel` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  `sales_channel_name` VARCHAR(45) NULL,
  `max_qty` VARCHAR(45) NULL,
  `applicable_from` VARCHAR(45) NULL,
  `applicable_to` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inv_db`.`product_has_saleschannel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inv_db`.`product_has_saleschannel` ;

CREATE TABLE IF NOT EXISTS `inv_db`.`product_has_saleschannel` (
  `id` INT NOT NULL,
  `sales_channel_id` INT NOT NULL,
  `uom` VARCHAR(45) NULL,
  `num_of_units` VARCHAR(45) BINARY NULL,
  `cost_price` VARCHAR(45) NULL,
  `margin` VARCHAR(45) NULL,
  `selling_price` VARCHAR(45) NULL,
  `sale_previleges_discount` VARCHAR(45) NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_has_saleschannel_sales_channel1_idx` (`sales_channel_id` ASC) VISIBLE,
  INDEX `fk_product_has_saleschannel_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_has_saleschannel_sales_channel1`
    FOREIGN KEY (`sales_channel_id`)
    REFERENCES `inv_db`.`sales_channel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_saleschannel_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `inv_db`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inv_db`.`store_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inv_db`.`store_type` ;

CREATE TABLE IF NOT EXISTS `inv_db`.`store_type` (
  `id` INT NOT NULL,
  `sture_type_name` VARCHAR(45) NULL,
  `note` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inv_db`.`store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inv_db`.`store` ;

CREATE TABLE IF NOT EXISTS `inv_db`.`store` (
  `id` INT NOT NULL,
  `store_name` VARCHAR(45) NULL,
  `parent_store` VARCHAR(45) NULL,
  `uom` VARCHAR(45) NOT NULL,
  `capacity` VARCHAR(45) NULL,
  `store_contact_person` VARCHAR(45) NULL,
  `mobile` VARCHAR(45) NULL,
  `store_type_id` INT NOT NULL,
  PRIMARY KEY (`id`, `store_type_id`),
  INDEX `fk_store_store_type1_idx` (`store_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_store_store_type1`
    FOREIGN KEY (`store_type_id`)
    REFERENCES `inv_db`.`store_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inv_db`.`location_has_store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inv_db`.`location_has_store` ;

CREATE TABLE IF NOT EXISTS `inv_db`.`location_has_store` (
  `id` INT NOT NULL,
  `location_id` INT NOT NULL,
  `store_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_location_has_store_location1_idx` (`location_id` ASC) VISIBLE,
  INDEX `fk_location_has_store_store1_idx` (`store_id` ASC) VISIBLE,
  CONSTRAINT `fk_location_has_store_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `inv_db`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_location_has_store_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `inv_db`.`store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inv_db`.`vehicle_master`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inv_db`.`vehicle_master` ;

CREATE TABLE IF NOT EXISTS `inv_db`.`vehicle_master` (
  `id` INT NOT NULL,
  `vehicle_reg_no` VARCHAR(45) NOT NULL,
  `note` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inv_db`.`drivers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inv_db`.`drivers` ;

CREATE TABLE IF NOT EXISTS `inv_db`.`drivers` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `note` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inv_db`.`vehicle_master_has_drivers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inv_db`.`vehicle_master_has_drivers` ;

CREATE TABLE IF NOT EXISTS `inv_db`.`vehicle_master_has_drivers` (
  `id` VARCHAR(45) NOT NULL,
  `vehicle_master_id` INT NOT NULL,
  `drivers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vehicle_master_has_drivers_drivers1_idx` (`drivers_id` ASC) VISIBLE,
  INDEX `fk_vehicle_master_has_drivers_vehicle_master1_idx` (`vehicle_master_id` ASC) VISIBLE,
  CONSTRAINT `fk_vehicle_master_has_drivers_vehicle_master1`
    FOREIGN KEY (`vehicle_master_id`)
    REFERENCES `inv_db`.`vehicle_master` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehicle_master_has_drivers_drivers1`
    FOREIGN KEY (`drivers_id`)
    REFERENCES `inv_db`.`drivers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inv_db`.`attribute_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inv_db`.`attribute_type` ;

CREATE TABLE IF NOT EXISTS `inv_db`.`attribute_type` (
  `id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `product_service_type` VARCHAR(45) NULL,
  `attribute_type_name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_attribute_type_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_attribute_type_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `inv_db`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inv_db`.`attribute`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inv_db`.`attribute` ;

CREATE TABLE IF NOT EXISTS `inv_db`.`attribute` (
  `id` INT NOT NULL,
  `attribute_type_id` INT NOT NULL,
  `attribute_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_attribute_attribute_type1_idx` (`attribute_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_attribute_attribute_type1`
    FOREIGN KEY (`attribute_type_id`)
    REFERENCES `inv_db`.`attribute_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
