<?php

declare(strict_types=1);

namespace Modules\Inventory\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class CustomerRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            // General — required fields
            // customer_code is auto-generated by the backend — never accepted from the client.
            'title'                        => ['required', 'string', 'max:20'],
            'customer_type'                => ['required', 'string', Rule::in(['Trade', 'Retail', 'Wholesale', 'Corporate'])],
            'customer_name'                => ['required', 'string', 'max:100'],
            'nic_passport_driving_licence' => ['required', 'string', 'max:50'],

            // General — optional
            'reference_no'                 => ['nullable', 'string', 'max:50'],
            'attachments'                  => ['nullable', 'string', 'max:255'],
            'br_no'                        => ['nullable', 'string', 'max:50'],
            'customer_tin'                 => ['nullable', 'string', 'max:50'],

            // Contact — required
            'customer_mobile'              => ['required', 'string', 'max:20'],

            // Contact — optional
            'customer_land_line'           => ['nullable', 'string', 'max:20'],
            'customer_email'               => ['nullable', 'email', 'max:100'],
            'customer_fax'                 => ['nullable', 'string', 'max:20'],

            // Billing address — required
            'billing_address_line1'        => ['required', 'string', 'max:100'],

            // Billing address — optional
            'billing_address_line2'        => ['nullable', 'string', 'max:100'],
            'billing_address_line3'        => ['nullable', 'string', 'max:100'],
            'billing_city'                 => ['nullable', 'string', 'max:50'],
            'billing_zip_postal'           => ['nullable', 'string', 'max:20'],
            'billing_state_province'       => ['nullable', 'string', 'max:50'],
            'billing_country'              => ['nullable', 'string', 'max:50'],

            // Shipping address
            'shipping_address_line1'       => ['nullable', 'string', 'max:100'],
            'shipping_address_line2'       => ['nullable', 'string', 'max:100'],
            'shipping_address_line3'       => ['nullable', 'string', 'max:100'],
            'shipping_city'                => ['nullable', 'string', 'max:50'],
            'shipping_zip_postal'          => ['nullable', 'string', 'max:20'],
            'shipping_state_province'      => ['nullable', 'string', 'max:50'],
            'shipping_country'             => ['nullable', 'string', 'max:50'],

            // Sales team
            'sale_manager'                 => ['nullable', 'string', 'max:100'],
            'sales_executive'              => ['nullable', 'string', 'max:100'],
            'sales_person'                 => ['nullable', 'string', 'max:100'],
        ];
    }

    public function attributes(): array
    {
        return [
            'title'                        => 'title',
            'customer_type'                => 'customer type',
            'customer_name'                => 'customer name',
            'nic_passport_driving_licence' => 'NIC / passport / driving licence',
            'reference_no'                 => 'reference number',
            'attachments'                  => 'attachments',
            'br_no'                        => 'BR number',
            'customer_tin'                 => 'customer TIN',
            'customer_mobile'              => 'customer mobile',
            'customer_land_line'           => 'land line',
            'customer_email'               => 'email',
            'customer_fax'                 => 'fax',
            'billing_address_line1'        => 'billing address line 1',
            'billing_address_line2'        => 'billing address line 2',
            'billing_address_line3'        => 'billing address line 3',
            'billing_city'                 => 'billing city',
            'billing_zip_postal'           => 'billing zip / postal',
            'billing_state_province'       => 'billing state / province',
            'billing_country'              => 'billing country',
            'shipping_address_line1'       => 'shipping address line 1',
            'shipping_address_line2'       => 'shipping address line 2',
            'shipping_address_line3'       => 'shipping address line 3',
            'shipping_city'                => 'shipping city',
            'shipping_zip_postal'          => 'shipping zip / postal',
            'shipping_state_province'      => 'shipping state / province',
            'shipping_country'             => 'shipping country',
            'sale_manager'                 => 'sale manager',
            'sales_executive'              => 'sales executive',
            'sales_person'                 => 'sales person',
        ];
    }
}
