<?php

declare(strict_types=1);

namespace Modules\Inventory\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;
use Modules\Inventory\Enums\ReturnCondition;
use Modules\Inventory\Enums\ReturnReason;

/**
 * Header + lines of a customer return. return_no is never accepted — it is generated by
 * CustomerReturnService. Returnable quantities are checked against the live invoice in
 * the service, not here.
 */
class StoreCustomerReturnRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    /** @return array<string, array<int, mixed>> */
    public function rules(): array
    {
        return [
            'return_date' => ['required', 'date'],
            'customer_id' => ['required', 'integer', 'exists:inv_customer_masters,id'],
            'invoice_id'  => ['required', 'integer', 'exists:inv_invoices,id'],
            'store_id'    => ['required', 'integer', 'exists:inv_stores,id'],
            'remarks'     => ['nullable', 'string', 'max:1000'],

            'items'                   => ['required', 'array', 'min:1'],
            'items.*.invoice_item_id' => ['required', 'integer', 'distinct'],
            // Manual (non-roll) lines carry a quantity; roll lines carry per-roll quantities instead.
            'items.*.quantity'        => ['nullable', 'numeric', 'min:0'],
            'items.*.reason'          => ['required', Rule::enum(ReturnReason::class)],
            'items.*.condition'       => ['required', Rule::enum(ReturnCondition::class)],
            'items.*.store_id'        => ['nullable', 'integer', 'exists:inv_stores,id'],
            'items.*.remarks'         => ['nullable', 'string', 'max:500'],

            'items.*.pieces'               => ['nullable', 'array'],
            'items.*.pieces.*.do_piece_id' => ['required_with:items.*.pieces', 'integer', 'distinct'],
            'items.*.pieces.*.quantity'    => ['required_with:items.*.pieces', 'numeric', 'gt:0'],
        ];
    }

    /** @return array<string, string> */
    public function attributes(): array
    {
        return [
            'customer_id'                  => 'customer',
            'invoice_id'                   => 'invoice',
            'store_id'                     => 'return store',
            'items.*.invoice_item_id'      => 'invoice line',
            'items.*.quantity'             => 'return quantity',
            'items.*.reason'               => 'reason',
            'items.*.condition'            => 'condition',
            'items.*.store_id'             => 'store',
            'items.*.pieces.*.do_piece_id' => 'roll',
            'items.*.pieces.*.quantity'    => 'roll return quantity',
        ];
    }

    public function withValidator(Validator $validator): void
    {
        $validator->after(function (Validator $validator): void {
            foreach ((array) $this->input('items', []) as $index => $item) {
                $hasPieces = !empty($item['pieces']);
                $quantity  = (float) ($item['quantity'] ?? 0);

                if (!$hasPieces && $quantity <= 0) {
                    $validator->errors()->add("items.{$index}.quantity", 'Enter the quantity being returned.');
                }
            }
        });
    }
}
