<?php

namespace Modules\Inventory\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CustomersSeeder extends Seeder
{
    public function run(): void
    {
        $customers = [
            // Corporate / Export
            [
                'customer_code'          => 'CUS-0001',
                'customer_type'          => 'Corporate',
                'title'                  => 'Mr.',
                'customer_name'          => 'Brandix Lanka Limited',
                'br_no'                  => 'BRX-001234',
                'customer_mobile'        => '+94 11 4600000',
                'customer_email'         => 'procurement@brandix.lk',
                'billing_address_line1'  => 'Brandix Apparel City',
                'billing_city'           => 'Hambantota',
                'billing_state_province' => 'Southern Province',
                'billing_country'        => 'Sri Lanka',
                'billing_zip_postal'     => '82000',
                'shipping_address_line1' => 'Brandix Apparel City',
                'shipping_city'          => 'Hambantota',
                'shipping_state_province'=> 'Southern Province',
                'shipping_country'       => 'Sri Lanka',
                'shipping_zip_postal'    => '82000',
                'sale_manager'           => 'Ruwan Samarakoon',
                'sales_executive'        => 'Kumari Perera',
            ],
            [
                'customer_code'          => 'CUS-0002',
                'customer_type'          => 'Corporate',
                'title'                  => 'Ms.',
                'customer_name'          => 'MAS Holdings (Pvt) Ltd',
                'br_no'                  => 'MAS-009876',
                'customer_mobile'        => '+94 11 5388000',
                'customer_email'         => 'fabric.buying@masholdings.com',
                'billing_address_line1'  => 'No. 52, Vauxhall Lane',
                'billing_city'           => 'Colombo',
                'billing_state_province' => 'Western Province',
                'billing_country'        => 'Sri Lanka',
                'billing_zip_postal'     => '00200',
                'shipping_address_line1' => 'No. 52, Vauxhall Lane',
                'shipping_city'          => 'Colombo',
                'shipping_state_province'=> 'Western Province',
                'shipping_country'       => 'Sri Lanka',
                'shipping_zip_postal'    => '00200',
                'sale_manager'           => 'Ruwan Samarakoon',
                'sales_executive'        => 'Tharindu Jayawardena',
            ],
            [
                'customer_code'          => 'CUS-0003',
                'customer_type'          => 'Wholesale',
                'title'                  => 'Mr.',
                'customer_name'          => 'H&M Sourcing Asia Ltd',
                'br_no'                  => 'HM-HK-4455',
                'customer_mobile'        => '+852 2828 8888',
                'customer_email'         => 'sourcing@hm-asia.com',
                'billing_address_line1'  => '15th Floor, Tower 2, Times Square',
                'billing_city'           => 'Hong Kong',
                'billing_state_province' => 'Causeway Bay',
                'billing_country'        => 'Hong Kong',
                'billing_zip_postal'     => '000000',
                'shipping_address_line1' => 'Via Colombo Port',
                'shipping_city'          => 'Colombo',
                'shipping_state_province'=> 'Western Province',
                'shipping_country'       => 'Sri Lanka',
                'shipping_zip_postal'    => '00100',
                'sale_manager'           => 'Ruwan Samarakoon',
                'sales_executive'        => 'Nimali Gunawardena',
            ],
            // Wholesale – Local
            [
                'customer_code'          => 'CUS-0004',
                'customer_type'          => 'Wholesale',
                'title'                  => 'Mr.',
                'customer_name'          => 'Pettah Textile Traders',
                'br_no'                  => 'PT-00567',
                'customer_mobile'        => '+94 77 2223344',
                'customer_email'         => 'pettahtextile@gmail.com',
                'billing_address_line1'  => 'No. 23, Main Street, Pettah',
                'billing_city'           => 'Colombo',
                'billing_state_province' => 'Western Province',
                'billing_country'        => 'Sri Lanka',
                'billing_zip_postal'     => '00100',
                'shipping_address_line1' => 'No. 23, Main Street, Pettah',
                'shipping_city'          => 'Colombo',
                'shipping_state_province'=> 'Western Province',
                'shipping_country'       => 'Sri Lanka',
                'shipping_zip_postal'    => '00100',
                'sale_manager'           => 'Ashan De Silva',
                'sales_executive'        => 'Kumari Perera',
            ],
            [
                'customer_code'          => 'CUS-0005',
                'customer_type'          => 'Wholesale',
                'title'                  => 'Mrs.',
                'customer_name'          => 'Kandy Fashion House',
                'br_no'                  => 'KFH-00234',
                'customer_mobile'        => '+94 81 2224455',
                'customer_email'         => 'orders@kandyfashion.lk',
                'billing_address_line1'  => 'No. 56, Dalada Veediya',
                'billing_city'           => 'Kandy',
                'billing_state_province' => 'Central Province',
                'billing_country'        => 'Sri Lanka',
                'billing_zip_postal'     => '20000',
                'shipping_address_line1' => 'No. 56, Dalada Veediya',
                'shipping_city'          => 'Kandy',
                'shipping_state_province'=> 'Central Province',
                'shipping_country'       => 'Sri Lanka',
                'shipping_zip_postal'    => '20000',
                'sale_manager'           => 'Ashan De Silva',
                'sales_executive'        => 'Tharindu Jayawardena',
            ],
            // Retail – Walk-in
            [
                'customer_code'          => 'CUS-0006',
                'customer_type'          => 'Retail',
                'title'                  => 'Ms.',
                'customer_name'          => 'Nilufar Boutique',
                'br_no'                  => null,
                'customer_mobile'        => '+94 77 9988776',
                'customer_email'         => 'nilufar.btq@gmail.com',
                'billing_address_line1'  => 'No. 12, Havelock Road',
                'billing_city'           => 'Colombo 5',
                'billing_state_province' => 'Western Province',
                'billing_country'        => 'Sri Lanka',
                'billing_zip_postal'     => '00500',
                'sale_manager'           => 'Dilini Seneviratne',
                'sales_executive'        => 'Kumari Perera',
            ],
            [
                'customer_code'          => 'CUS-0007',
                'customer_type'          => 'Retail',
                'title'                  => 'Mr.',
                'customer_name'          => 'Galle Garment Studio',
                'br_no'                  => 'GGS-0089',
                'customer_mobile'        => '+94 91 2236677',
                'customer_email'         => 'gallegarmentstudio@yahoo.com',
                'billing_address_line1'  => 'No. 8, Wakwella Road',
                'billing_city'           => 'Galle',
                'billing_state_province' => 'Southern Province',
                'billing_country'        => 'Sri Lanka',
                'billing_zip_postal'     => '80000',
                'sale_manager'           => 'Ashan De Silva',
                'sales_executive'        => 'Nimali Gunawardena',
            ],
            [
                'customer_code'          => 'CUS-0008',
                'customer_type'          => 'Trade',
                'title'                  => 'Mr.',
                'customer_name'          => 'Colombo Uniform Suppliers',
                'br_no'                  => 'CUS-TRD-0033',
                'customer_mobile'        => '+94 11 2756644',
                'customer_email'         => 'uniforms.col@gmail.com',
                'billing_address_line1'  => 'No. 4, Maligawatte Road',
                'billing_city'           => 'Colombo 10',
                'billing_state_province' => 'Western Province',
                'billing_country'        => 'Sri Lanka',
                'billing_zip_postal'     => '01000',
                'sale_manager'           => 'Ashan De Silva',
                'sales_executive'        => 'Tharindu Jayawardena',
            ],
        ];

        foreach ($customers as $customer) {
            DB::table('inv_customer_masters')->updateOrInsert(
                ['customer_code' => $customer['customer_code']],
                array_merge($customer, [
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }
    }
}
