<?php

namespace Modules\Inventory\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SuppliersSeeder extends Seeder
{
    public function run(): void
    {
        $suppliers = [
            // Grey Fabric Suppliers
            [
                'supplier_code'              => 'SUP-0001',
                'supplier_type'              => 'Grey Fabric',
                'supplier_name'              => 'Coats Thread Lanka (Pvt) Ltd',
                'check_writer_name'          => 'Coats Thread Lanka',
                'mobile'                     => '+94 11 4600100',
                'email'                      => 'procurement@coats.lk',
                'website'                    => 'https://www.coats.com',
                'bil_address_line_1'         => 'No. 39, Dam Street',
                'bil_city'                   => 'Colombo',
                'bil_country'                => 'Sri Lanka',
                'bil_state_province'         => 'Western Province',
                'bil_postal_code'            => '00100',
                'tax_type'                   => 'VAT',
                'tax_no'                     => 'VAT-CTL-221100',
                'credit_limit'               => 5000000.00,
                'credit_period'              => 45,
                'privileges_discount'        => 2.50,
                'bank_name'                  => 'Commercial Bank of Ceylon',
                'bank_branch'                => 'Pettah',
                'bank_acc_holder_name'       => 'Coats Thread Lanka (Pvt) Ltd',
                'bank_acc_no'                => '8001234567',
                'contact_person_name'        => 'Mahesh Jayawardena',
                'contact_person_designation' => 'Sales Manager',
                'contact_person_mobile'      => '+94 77 1002233',
                'contact_person_email'       => 'mahesh.j@coats.lk',
            ],
            [
                'supplier_code'              => 'SUP-0002',
                'supplier_type'              => 'Grey Fabric',
                'supplier_name'              => 'Jinxing Textile Co., Ltd',
                'check_writer_name'          => 'Jinxing Textile',
                'mobile'                     => '+86 512 6889 0000',
                'email'                      => 'export@jinxingtextile.com',
                'website'                    => 'https://www.jinxingtextile.com',
                'bil_address_line_1'         => '88 Suzhou Industrial Park',
                'bil_city'                   => 'Suzhou',
                'bil_country'                => 'China',
                'bil_state_province'         => 'Jiangsu',
                'bil_postal_code'            => '215100',
                'tax_type'                   => 'None',
                'credit_limit'               => 10000000.00,
                'credit_period'              => 60,
                'privileges_discount'        => 3.00,
                'bank_name'                  => 'Bank of China',
                'bank_branch'                => 'Suzhou Branch',
                'bank_acc_holder_name'       => 'Jinxing Textile Co., Ltd',
                'bank_acc_no'                => 'CNY10098765432',
                'contact_person_name'        => 'Li Wei',
                'contact_person_designation' => 'Export Manager',
                'contact_person_mobile'      => '+86 138 0512 8899',
                'contact_person_email'       => 'liwei@jinxingtextile.com',
            ],
            // Yarn Suppliers
            [
                'supplier_code'              => 'SUP-0003',
                'supplier_type'              => 'Yarn',
                'supplier_name'              => 'Prahladrai & Sons (Yarn Traders)',
                'check_writer_name'          => 'Prahladrai & Sons',
                'mobile'                     => '+91 22 2345 6789',
                'email'                      => 'yarn@prahladsons.in',
                'bil_address_line_1'         => '14, Kalbadevi Road',
                'bil_city'                   => 'Mumbai',
                'bil_country'                => 'India',
                'bil_state_province'         => 'Maharashtra',
                'bil_postal_code'            => '400002',
                'tax_type'                   => 'GST',
                'tax_no'                     => 'GSTIN-27AAJCP0000K1ZO',
                'credit_limit'               => 7500000.00,
                'credit_period'              => 30,
                'privileges_discount'        => 1.50,
                'bank_name'                  => 'State Bank of India',
                'bank_branch'                => 'Kalbadevi',
                'bank_acc_holder_name'       => 'Prahladrai & Sons',
                'bank_acc_no'                => 'SBI99887766554',
                'contact_person_name'        => 'Ramesh Prahladrai',
                'contact_person_designation' => 'Partner',
                'contact_person_mobile'      => '+91 98201 12345',
                'contact_person_email'       => 'ramesh@prahladsons.in',
            ],
            [
                'supplier_code'              => 'SUP-0004',
                'supplier_type'              => 'Yarn',
                'supplier_name'              => 'Lanka Yarn Mills (Pvt) Ltd',
                'check_writer_name'          => 'Lanka Yarn Mills',
                'mobile'                     => '+94 37 2220011',
                'email'                      => 'sales@lankayarnmills.lk',
                'bil_address_line_1'         => 'No. 110, Kandy Road',
                'bil_city'                   => 'Kurunegala',
                'bil_country'                => 'Sri Lanka',
                'bil_state_province'         => 'North Western Province',
                'bil_postal_code'            => '60000',
                'tax_type'                   => 'VAT',
                'tax_no'                     => 'VAT-LYM-334455',
                'credit_limit'               => 3000000.00,
                'credit_period'              => 30,
                'bank_name'                  => 'Peoples Bank',
                'bank_branch'                => 'Kurunegala',
                'bank_acc_holder_name'       => 'Lanka Yarn Mills (Pvt) Ltd',
                'bank_acc_no'                => 'PB55443322110',
                'contact_person_name'        => 'Senaka Wijeratne',
                'contact_person_designation' => 'Sales Executive',
                'contact_person_mobile'      => '+94 77 5544332',
                'contact_person_email'       => 'senaka@lankayarnmills.lk',
            ],
            // Dye & Chemical Suppliers
            [
                'supplier_code'              => 'SUP-0005',
                'supplier_type'              => 'Dyes & Chemicals',
                'supplier_name'              => 'Huntsman Textile Effects (Lanka)',
                'check_writer_name'          => 'Huntsman Textile Effects',
                'mobile'                     => '+94 11 4601500',
                'email'                      => 'textileeffects.lk@huntsman.com',
                'website'                    => 'https://www.huntsman.com/textile_effects',
                'bil_address_line_1'         => 'No. 7, Glennie Street',
                'bil_city'                   => 'Colombo',
                'bil_country'                => 'Sri Lanka',
                'bil_state_province'         => 'Western Province',
                'bil_postal_code'            => '00200',
                'tax_type'                   => 'VAT',
                'tax_no'                     => 'VAT-HTE-556677',
                'credit_limit'               => 4000000.00,
                'credit_period'              => 45,
                'privileges_discount'        => 5.00,
                'bank_name'                  => 'HSBC Sri Lanka',
                'bank_branch'                => 'Colombo Fort',
                'bank_acc_holder_name'       => 'Huntsman Textile Effects (Lanka)',
                'bank_acc_no'                => 'HSBC77665544332',
                'contact_person_name'        => 'Dinesh Kumara',
                'contact_person_designation' => 'Technical Sales Manager',
                'contact_person_mobile'      => '+94 76 2200110',
                'contact_person_email'       => 'dinesh.kumara@huntsman.com',
            ],
            [
                'supplier_code'              => 'SUP-0006',
                'supplier_type'              => 'Dyes & Chemicals',
                'supplier_name'              => 'Archroma Lanka (Pvt) Ltd',
                'check_writer_name'          => 'Archroma Lanka',
                'mobile'                     => '+94 11 4725000',
                'email'                      => 'lanka@archroma.com',
                'website'                    => 'https://www.archroma.com',
                'bil_address_line_1'         => 'No. 36, D.R. Wijewardena Mawatha',
                'bil_city'                   => 'Colombo',
                'bil_country'                => 'Sri Lanka',
                'bil_state_province'         => 'Western Province',
                'bil_postal_code'            => '00100',
                'tax_type'                   => 'VAT',
                'tax_no'                     => 'VAT-ARCH-998877',
                'credit_limit'               => 6000000.00,
                'credit_period'              => 60,
                'bank_name'                  => 'Deutsche Bank AG',
                'bank_branch'                => 'Colombo',
                'bank_acc_holder_name'       => 'Archroma Lanka (Pvt) Ltd',
                'bank_acc_no'                => 'DB99887766554',
                'contact_person_name'        => 'Priyantha Gunaratne',
                'contact_person_designation' => 'Country Manager',
                'contact_person_mobile'      => '+94 71 8877665',
                'contact_person_email'       => 'priyantha.g@archroma.com',
            ],
            // Packing Supplier
            [
                'supplier_code'              => 'SUP-0007',
                'supplier_type'              => 'Packing Materials',
                'supplier_name'              => 'Printcare PLC',
                'check_writer_name'          => 'Printcare PLC',
                'mobile'                     => '+94 11 2390000',
                'email'                      => 'packaging@printcare.lk',
                'website'                    => 'https://www.printcare.lk',
                'bil_address_line_1'         => 'No. 9, Sir Razik Fareed Mawatha',
                'bil_city'                   => 'Colombo',
                'bil_country'                => 'Sri Lanka',
                'bil_state_province'         => 'Western Province',
                'bil_postal_code'            => '01000',
                'tax_type'                   => 'VAT',
                'tax_no'                     => 'VAT-PLC-112233',
                'credit_limit'               => 2000000.00,
                'credit_period'              => 30,
                'bank_name'                  => 'Nations Trust Bank',
                'bank_branch'                => 'Union Place',
                'bank_acc_holder_name'       => 'Printcare PLC',
                'bank_acc_no'                => 'NTB33221100987',
                'contact_person_name'        => 'Kasun Aluthge',
                'contact_person_designation' => 'Account Manager',
                'contact_person_mobile'      => '+94 77 3344556',
                'contact_person_email'       => 'kasun.a@printcare.lk',
            ],
            // Machinery & Spare Parts
            [
                'supplier_code'              => 'SUP-0008',
                'supplier_type'              => 'Machinery & Spares',
                'supplier_name'              => 'Picanol Asia Pacific Ltd',
                'check_writer_name'          => 'Picanol Asia Pacific',
                'mobile'                     => '+852 2810 7777',
                'email'                      => 'asiaservice@picanol.be',
                'website'                    => 'https://www.picanol.be',
                'bil_address_line_1'         => 'Suite 2201, One Pacific Place',
                'bil_city'                   => 'Hong Kong',
                'bil_country'                => 'Hong Kong',
                'bil_state_province'         => 'Admiralty',
                'bil_postal_code'            => '000000',
                'tax_type'                   => 'None',
                'credit_limit'               => 20000000.00,
                'credit_period'              => 90,
                'bank_name'                  => 'HSBC Hong Kong',
                'bank_branch'                => 'Hong Kong Main',
                'bank_acc_holder_name'       => 'Picanol Asia Pacific Ltd',
                'bank_acc_no'                => 'HSBCHK112233445',
                'contact_person_name'        => 'David Chan',
                'contact_person_designation' => 'Regional Sales Director',
                'contact_person_mobile'      => '+852 9988 7766',
                'contact_person_email'       => 'david.chan@picanol.be',
            ],
        ];

        foreach ($suppliers as $supplier) {
            DB::table('inv_supplier_masters')->updateOrInsert(
                ['supplier_code' => $supplier['supplier_code']],
                array_merge($supplier, [
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }
    }
}
