<?php

declare(strict_types=1);

namespace Modules\Inventory\Http\Controllers;

use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Modules\Inventory\Services\AvailableStockReportService;
use Modules\Inventory\Support\Money;
use Symfony\Component\HttpFoundation\StreamedResponse;

/**
 * PDF / CSV exports of the Available Stock report. Both re-run the same service the
 * on-screen table uses, so the printed sheet is the on-screen sheet — including the
 * Selling Price column, which appears in the export only when the admin ticked
 * "Include Selling Price" in the filter panel.
 */
class AvailableStockExportController extends Controller
{
    public function __construct(private readonly AvailableStockReportService $service)
    {
        $this->middleware('permission:view_reports');
    }

    public function pdf(Request $request): Response
    {
        $data = $this->service->build($this->validated($request));

        $pdf = Pdf::loadView('inventory::pdf.available_stock', $data)
            ->setPaper('a4', 'portrait')
            ->setOptions([
                'defaultFont'          => 'DejaVu Sans',
                'isHtml5ParserEnabled' => true,
                'isPhpEnabled'         => false,
                'dpi'                  => 150,
                'defaultPaperSize'     => 'a4',
            ]);

        return $pdf->download($this->filename('pdf'));
    }

    public function csv(Request $request): StreamedResponse
    {
        $data = $this->service->build($this->validated($request));

        return response()->streamDownload(function () use ($data): void {
            $out       = fopen('php://output', 'w');
            $header    = $data['header'];
            $withPrice = (bool) $header['include_selling_price'];

            fputcsv($out, ['Available Stock Report']);
            fputcsv($out, [$header['company_name'], $header['company_address'], $header['company_email']]);
            fputcsv($out, []);
            fputcsv($out, ['Location', $header['location_name'] ?? 'All', 'Category', $header['category_name'] ?? 'All']);
            fputcsv($out, ['Product', $header['product_name'] ?? 'All', 'Colour', $header['attribute_name'] ?? 'All']);
            fputcsv($out, ['Generated By', $header['generated_by'], 'Generated Time', $header['generated_at']]);
            fputcsv($out, []);

            $columns = ['Product', 'Colour', 'Available Qty', 'Unit'];

            if ($withPrice) {
                $columns[] = Money::label('Selling Price');
            }

            fputcsv($out, $columns);

            foreach ($data['rows'] as $row) {
                $line = [
                    $row['product_name'],
                    $row['attribute_name'] ?? '-',
                    $row['available_qty'],
                    $row['unit'] ?? '-',
                ];

                if ($withPrice) {
                    // Blank, not 0 — an uncosted, unlisted product has no price, and a
                    // zero there reads as "free" to whoever opens the sheet.
                    $line[] = $row['selling_price'] ?? '';
                }

                fputcsv($out, $line);
            }

            fclose($out);
        }, $this->filename('csv'), [
            'Content-Type' => 'text/csv; charset=UTF-8',
        ]);
    }

    /** @return array<string, mixed> */
    private function validated(Request $request): array
    {
        $request->validate([
            'product_id'            => ['nullable', 'integer', 'exists:inv_products,id'],
            'category_id'           => ['nullable', 'integer', 'exists:inv_categories,id'],
            'attribute_id'          => ['nullable', 'integer', 'exists:inv_attributes,id'],
            'location_id'           => ['nullable', 'integer', 'exists:inv_locations,id'],
            'include_selling_price' => ['nullable', 'boolean'],
        ]);

        return [
            'product_id'            => $request->integer('product_id') ?: null,
            'category_id'           => $request->integer('category_id') ?: null,
            'attribute_id'          => $request->integer('attribute_id') ?: null,
            'location_id'           => $request->integer('location_id') ?: null,
            'include_selling_price' => $request->boolean('include_selling_price'),
        ];
    }

    private function filename(string $extension): string
    {
        return 'AvailableStock_' . now()->format('Ymd') . '.' . $extension;
    }
}
