<?php

declare(strict_types=1);

namespace Modules\Inventory\Http\Controllers;

use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Symfony\Component\HttpFoundation\StreamedResponse;
use Modules\Inventory\Services\BinCardService;

class BinCardExportController extends Controller
{
    public function __construct(private readonly BinCardService $service)
    {
        $this->middleware('permission:view_reports');
    }

    public function pdf(Request $request): Response
    {
        $data = $this->service->build($this->validated($request));

        $pdf = Pdf::loadView('inventory::pdf.bin_card', $data)
            ->setPaper('a4', 'portrait')
            ->setOptions([
                'defaultFont'          => 'DejaVu Sans',
                'isHtml5ParserEnabled' => true,
                'isPhpEnabled'         => false,
                'dpi'                  => 150,
                'defaultPaperSize'     => 'a4',
            ]);

        return $pdf->download($this->filename($data, 'pdf'));
    }

    public function csv(Request $request): StreamedResponse
    {
        $data = $this->service->build($this->validated($request));

        return response()->streamDownload(function () use ($data): void {
            $out    = fopen('php://output', 'w');
            $header = $data['header'];

            fputcsv($out, ['Bin Card Report']);
            fputcsv($out, [$header['company_name'], $header['company_address'], $header['company_email']]);
            fputcsv($out, []);
            fputcsv($out, ['Product Code', $header['product_code'], 'Product Name', $header['product_name']]);
            fputcsv($out, ['Location', $header['location_name'] ?? 'All', 'Store', $header['store_name'] ?? 'All']);
            fputcsv($out, ['Period', ($header['date_from'] ?? 'Beginning') . ' - ' . ($header['date_to'] ?? 'To Date'), 'Stock In Hand', $header['stock_in_hand']]);
            fputcsv($out, ['UOM', $header['uom'] ?? '', 'Currency', $header['currency_code'] . ' (' . $header['currency_symbol'] . ')']);
            fputcsv($out, ['Reorder Level', $header['reorder_level'], 'Reorder Qty', $header['reorder_qty']]);
            fputcsv($out, ['Generated By', $header['generated_by'], 'Generated Time', $header['generated_at']]);
            fputcsv($out, []);

            $uomTag = $header['uom'] ? " ({$header['uom']})" : '';
            fputcsv($out, [
                'Date', 'Description', 'Document No', 'Colour',
                "Unit Price ({$header['currency_code']})",
                "Stock IN{$uomTag}", "Stock Out{$uomTag}", "Stock Balance{$uomTag}",
            ]);

            if ($data['opening']['show']) {
                fputcsv($out, [$header['date_from'], 'Opening Balance', '', '', '', '', '', $data['opening']['balance']]);
            }

            foreach ($data['rows'] as $row) {
                fputcsv($out, [$row['date'], $row['description'], $row['document_no'], $row['color'] ?? '', $row['unit_price'] ?? '', $row['qty_in'], $row['qty_out'], $row['balance']]);
            }

            fputcsv($out, ['', '', '', '', 'Total', $data['summary']['total_in'], $data['summary']['total_out'], $data['summary']['closing_balance']]);

            fclose($out);
        }, $this->filename($data, 'csv'), [
            'Content-Type' => 'text/csv; charset=UTF-8',
        ]);
    }

    /** @return array<string, mixed> */
    private function validated(Request $request): array
    {
        $request->validate([
            'product_id'   => ['required', 'integer', 'exists:inv_products,id'],
            'attribute_id' => ['nullable', 'integer', 'exists:inv_attributes,id'],
            'location_id'  => ['nullable', 'integer', 'exists:inv_locations,id'],
            'store_id'     => ['nullable', 'integer', 'exists:inv_stores,id'],
            'date_from'    => ['nullable', 'date'],
            'date_to'      => ['nullable', 'date', 'after_or_equal:date_from'],
        ]);

        return $request->only(['product_id', 'attribute_id', 'location_id', 'store_id', 'date_from', 'date_to']);
    }

    /** @param array<string, mixed> $data */
    private function filename(array $data, string $extension): string
    {
        $code = $data['header']['product_code'] ?: 'product';

        return 'BinCard_' . $code . '_' . now()->format('Ymd') . '.' . $extension;
    }
}
