<?php

declare(strict_types=1);

namespace Modules\Inventory\Http\Controllers;

use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Symfony\Component\HttpFoundation\StreamedResponse;
use Modules\Inventory\Services\OutstandingSummaryReportService;

class OutstandingSummaryExportController extends Controller
{
    public function __construct(private readonly OutstandingSummaryReportService $service)
    {
        $this->middleware('permission:view_reports');
    }

    public function pdf(Request $request): Response
    {
        $data = $this->service->build($this->validated($request));

        $pdf = Pdf::loadView('inventory::pdf.outstanding_summary', $data)
            ->setPaper('a4', 'portrait')
            ->setOptions([
                'defaultFont'          => 'DejaVu Sans',
                'isHtml5ParserEnabled' => true,
                'isPhpEnabled'         => false,
                'dpi'                  => 150,
                'defaultPaperSize'     => 'a4',
            ]);

        return $pdf->download($this->filename('pdf'));
    }

    public function csv(Request $request): StreamedResponse
    {
        $data = $this->service->build($this->validated($request));

        return response()->streamDownload(function () use ($data): void {
            $out    = fopen('php://output', 'w');
            $header = $data['header'];

            fputcsv($out, ['Outstanding Summary']);
            fputcsv($out, [$header['company_name'], $header['company_address'], $header['company_email']]);
            fputcsv($out, []);
            fputcsv($out, ['As Of', $header['as_of'], 'Customer', $header['customer_name'] ?? 'All', 'Overdue Only', $header['overdue_only'] ? 'Yes' : 'No']);
            fputcsv($out, ['Generated By', $header['generated_by'], 'Generated Time', $header['generated_at']]);
            fputcsv($out, []);
            fputcsv($out, ['Customer', 'Invoice No', 'Invoice Date', 'Due Date', 'Days Overdue', 'SO No', 'DO No', 'Amount', 'Received', 'Outstanding']);

            foreach ($data['customers'] as $customer) {
                foreach ($customer['invoices'] as $inv) {
                    fputcsv($out, [
                        $customer['customer_name'],
                        $inv['invoice_no'],
                        $inv['invoice_date'],
                        $inv['due_date'] ?? '-',
                        $inv['days_overdue'] ?? '-',
                        $inv['so_no'] ?? '-',
                        $inv['do_no'] ?? '-',
                        $inv['amount'],
                        $inv['received'],
                        $inv['outstanding'],
                    ]);
                }
                fputcsv($out, ['', '', '', '', '', '', 'Total ' . $customer['customer_name'], '', '', $customer['customer_outstanding']]);
                fputcsv($out, []);
            }

            $summary = $data['summary'];
            fputcsv($out, ['', '', '', '', '', '', 'Grand Total', '', '', $summary['total_outstanding']]);

            fclose($out);
        }, $this->filename('csv'), [
            'Content-Type' => 'text/csv; charset=UTF-8',
        ]);
    }

    /** @return array<string, mixed> */
    private function validated(Request $request): array
    {
        $request->validate([
            'customer_id'  => ['nullable', 'integer', 'exists:inv_customer_masters,id'],
            'overdue_only' => ['nullable', 'boolean'],
        ]);

        return [
            'customer_id'  => $request->integer('customer_id') ?: null,
            'overdue_only' => $request->boolean('overdue_only'),
        ];
    }

    private function filename(string $extension): string
    {
        return 'OutstandingSummary_' . now()->format('Ymd') . '.' . $extension;
    }
}
