<?php

declare(strict_types=1);

namespace Modules\Inventory\Http\Controllers;

use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Symfony\Component\HttpFoundation\StreamedResponse;
use Modules\Inventory\Services\SalesByItemSummaryService;

class SalesByItemSummaryExportController extends Controller
{
    public function __construct(private readonly SalesByItemSummaryService $service)
    {
        $this->middleware('permission:view_reports');
    }

    public function pdf(Request $request): Response
    {
        $data = $this->service->build($this->validated($request));

        $pdf = Pdf::loadView('inventory::pdf.sales_by_item_summary', $data)
            ->setPaper('a4', 'portrait')
            ->setOptions([
                'defaultFont'          => 'DejaVu Sans',
                'isHtml5ParserEnabled' => true,
                'isPhpEnabled'         => false,
                'dpi'                  => 150,
                'defaultPaperSize'     => 'a4',
            ]);

        return $pdf->download($this->filename('pdf'));
    }

    public function csv(Request $request): StreamedResponse
    {
        $data = $this->service->build($this->validated($request));

        return response()->streamDownload(function () use ($data): void {
            $out    = fopen('php://output', 'w');
            $header = $data['header'];

            fputcsv($out, ['Sales By Item Summary']);
            fputcsv($out, [$header['company_name'], $header['company_address'], $header['company_email']]);
            fputcsv($out, []);
            fputcsv($out, ['Period', ($header['date_from'] ?? 'Beginning') . ' - ' . ($header['date_to'] ?? 'To Date'), 'Category', $header['category_name'] ?? 'All']);
            fputcsv($out, ['Location', $header['location_name'] ?? 'All']);
            fputcsv($out, ['Generated By', $header['generated_by'], 'Generated Time', $header['generated_at']]);
            fputcsv($out, []);
            fputcsv($out, ['Category', 'Product', 'Colour', 'Unit', 'Qty', 'Amount']);

            foreach ($data['categories'] as $category) {
                foreach ($category['items'] as $item) {
                    fputcsv($out, [
                        $category['category_name'],
                        $item['product_name'],
                        $item['attribute_name'] ?? '-',
                        $item['unit'] ?? '-',
                        $item['quantity'],
                        $item['amount'],
                    ]);
                }
                // Qty left blank — a category can mix units (Kg, M, Yards), so a summed qty would be meaningless.
                fputcsv($out, ['', '', '', 'Total ' . $category['category_name'], '', $category['category_amount']]);
                fputcsv($out, []);
            }

            $summary = $data['summary'];
            fputcsv($out, ['', '', '', 'Grand Total', $summary['total_qty'], $summary['total_amount']]);

            fclose($out);
        }, $this->filename('csv'), [
            'Content-Type' => 'text/csv; charset=UTF-8',
        ]);
    }

    /** @return array<string, mixed> */
    private function validated(Request $request): array
    {
        $request->validate([
            'location_id' => ['nullable', 'integer', 'exists:inv_locations,id'],
            'category_id' => ['nullable', 'integer', 'exists:inv_categories,id'],
            'date_from'   => ['nullable', 'date'],
            'date_to'     => ['nullable', 'date', 'after_or_equal:date_from'],
        ]);

        return $request->only(['location_id', 'category_id', 'date_from', 'date_to']);
    }

    private function filename(string $extension): string
    {
        return 'SalesByItemSummary_' . now()->format('Ymd') . '.' . $extension;
    }
}
