<?php

declare(strict_types=1);

namespace Modules\Inventory\Http\Controllers;

use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Symfony\Component\HttpFoundation\StreamedResponse;
use Modules\Inventory\Services\SalesSummaryReportService;

class SalesSummaryExportController extends Controller
{
    public function __construct(private readonly SalesSummaryReportService $service)
    {
        $this->middleware('permission:view_reports');
    }

    public function pdf(Request $request): Response
    {
        $data = $this->service->build($this->validated($request));

        $pdf = Pdf::loadView('inventory::pdf.sales_summary', $data)
            ->setPaper('a4', 'portrait')
            ->setOptions([
                'defaultFont'          => 'DejaVu Sans',
                'isHtml5ParserEnabled' => true,
                'isPhpEnabled'         => false,
                'dpi'                  => 150,
                'defaultPaperSize'     => 'a4',
            ]);

        return $pdf->download($this->filename('pdf'));
    }

    public function csv(Request $request): StreamedResponse
    {
        $data = $this->service->build($this->validated($request));

        return response()->streamDownload(function () use ($data): void {
            $out    = fopen('php://output', 'w');
            $header = $data['header'];

            fputcsv($out, ['Sales Summary']);
            fputcsv($out, [$header['company_name'], $header['company_address'], $header['company_email']]);
            fputcsv($out, []);
            fputcsv($out, ['Period', ($header['date_from'] ?? 'Beginning') . ' - ' . ($header['date_to'] ?? 'To Date')]);
            fputcsv($out, ['Number of Bills', $header['bill_count'], 'Net Sale', $header['net_sale']]);
            fputcsv($out, ['Cash Sale', $header['cash_sale'], 'Non Cash Sale', $header['non_cash_sale'], 'Credit Sale', $header['credit_sale']]);
            fputcsv($out, ['Generated By', $header['generated_by'], 'Generated Time', $header['generated_at']]);
            fputcsv($out, []);
            fputcsv($out, ['Date', 'Cash', 'Credit', 'Cheque', 'Bank Deposit', 'Cards', 'Total Sales']);

            foreach ($data['rows'] as $row) {
                fputcsv($out, [
                    $row['date'],
                    $row['cash'],
                    $row['credit'],
                    $row['cheque'],
                    $row['bank_deposit'],
                    $row['cards'],
                    $row['total_sales'],
                ]);
            }

            $summary = $data['summary'];
            fputcsv($out, [
                'Total',
                $summary['cash'],
                $summary['credit'],
                $summary['cheque'],
                $summary['bank_deposit'],
                $summary['cards'],
                $summary['total_sales'],
            ]);

            fclose($out);
        }, $this->filename('csv'), [
            'Content-Type' => 'text/csv; charset=UTF-8',
        ]);
    }

    /** @return array<string, mixed> */
    private function validated(Request $request): array
    {
        $request->validate([
            'date_from' => ['nullable', 'date'],
            'date_to'   => ['nullable', 'date', 'after_or_equal:date_from'],
        ]);

        return $request->only(['date_from', 'date_to']);
    }

    private function filename(string $extension): string
    {
        return 'SalesSummary_' . now()->format('Ymd') . '.' . $extension;
    }
}
