<?php

declare(strict_types=1);

namespace Modules\Inventory\Http\Controllers;

use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Symfony\Component\HttpFoundation\StreamedResponse;
use Modules\Inventory\Services\SalesByItemDetailSummaryService;

class SalesByItemDetailSummaryExportController extends Controller
{
    public function __construct(private readonly SalesByItemDetailSummaryService $service)
    {
        $this->middleware('permission:view_reports');
    }

    public function pdf(Request $request): Response
    {
        $data = $this->service->build($this->validated($request));

        $pdf = Pdf::loadView('inventory::pdf.sales_by_item_detail_summary', $data)
            ->setPaper('a4', 'landscape')
            ->setOptions([
                'defaultFont'          => 'DejaVu Sans',
                'isHtml5ParserEnabled' => true,
                'isPhpEnabled'         => false,
                'dpi'                  => 150,
                'defaultPaperSize'     => 'a4',
            ]);

        return $pdf->download($this->filename('pdf'));
    }

    public function csv(Request $request): StreamedResponse
    {
        $data = $this->service->build($this->validated($request));

        return response()->streamDownload(function () use ($data): void {
            $out    = fopen('php://output', 'w');
            $header = $data['header'];

            fputcsv($out, ['Sales By Item Detail Summary']);
            fputcsv($out, [$header['company_name'], $header['company_address'], $header['company_email']]);
            fputcsv($out, []);
            fputcsv($out, ['Period', $header['date_from'] . ' - ' . $header['date_to'], 'Category', $header['category_name'] ?? 'All']);
            fputcsv($out, ['Product', $header['product_name'] ?? 'All']);
            fputcsv($out, ['Generated By', $header['generated_by'], 'Generated Time', $header['generated_at']]);
            fputcsv($out, []);
            fputcsv($out, ['Category', 'Description', 'Colour', 'Type', 'Date', 'Number', 'Customer Name', 'Unit', 'Qty', 'Price', 'Amount']);

            foreach ($data['categories'] as $category) {
                foreach ($category['products'] as $product) {
                    foreach ($product['transactions'] as $txn) {
                        fputcsv($out, [
                            $category['category_name'],
                            $product['product_name'],
                            $txn['attribute_name'] ?? '-',
                            $txn['type'],
                            $txn['date'],
                            $txn['number'],
                            $txn['customer_name'],
                            $txn['unit'] ?? '-',
                            $txn['quantity'],
                            $txn['price'],
                            $txn['amount'],
                        ]);
                    }
                    // Qty left blank — a product's transactions can carry different units, so a summed qty would be meaningless.
                    fputcsv($out, ['', '', '', '', '', '', 'Total ' . $product['product_name'], '', '', '', $product['product_amount']]);
                }
                fputcsv($out, ['', '', '', '', '', '', 'Total ' . $category['category_name'], '', '', '', $category['category_amount']]);
                fputcsv($out, []);
            }

            $summary = $data['summary'];
            fputcsv($out, ['', '', '', '', '', '', 'Grand Total', '', $summary['total_qty'], '', $summary['total_amount']]);

            fclose($out);
        }, $this->filename('csv'), [
            'Content-Type' => 'text/csv; charset=UTF-8',
        ]);
    }

    /** @return array<string, mixed> */
    private function validated(Request $request): array
    {
        $request->validate([
            'date_from'   => ['required', 'date'],
            'date_to'     => ['required', 'date', 'after_or_equal:date_from'],
            'category_id' => ['nullable', 'integer', 'exists:inv_categories,id'],
            'product_id'  => ['nullable', 'integer', 'exists:inv_products,id'],
        ]);

        return $request->only(['date_from', 'date_to', 'category_id', 'product_id']);
    }

    private function filename(string $extension): string
    {
        return 'SalesByItemDetailSummary_' . now()->format('Ymd') . '.' . $extension;
    }
}
