<?php

declare(strict_types=1);

namespace Modules\Inventory\Http\Controllers;

use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Symfony\Component\HttpFoundation\StreamedResponse;
use Modules\Inventory\Services\StockMovementSummaryService;

class StockMovementSummaryExportController extends Controller
{
    public function __construct(private readonly StockMovementSummaryService $service)
    {
        $this->middleware('permission:view_reports');
    }

    public function pdf(Request $request): Response
    {
        $data = $this->service->build($this->validated($request));

        $pdf = Pdf::loadView('inventory::pdf.stock_movement_summary', $data)
            ->setPaper('a4', 'landscape')
            ->setOptions([
                'defaultFont'          => 'DejaVu Sans',
                'isHtml5ParserEnabled' => true,
                'isPhpEnabled'         => false,
                'dpi'                  => 150,
                'defaultPaperSize'     => 'a4',
            ]);

        return $pdf->download($this->filename('pdf'));
    }

    public function csv(Request $request): StreamedResponse
    {
        $data = $this->service->build($this->validated($request));

        return response()->streamDownload(function () use ($data): void {
            $out    = fopen('php://output', 'w');
            $header = $data['header'];

            fputcsv($out, ['Stock Movement Summary']);
            fputcsv($out, [$header['company_name'], $header['company_address'], $header['company_email']]);
            fputcsv($out, []);
            fputcsv($out, ['Period', ($header['date_from'] ?? 'Beginning') . ' - ' . ($header['date_to'] ?? 'To Date'), 'Category', $header['category_name'] ?? 'All']);
            fputcsv($out, ['Location', $header['location_name'] ?? 'All', 'Warehouse', $header['store_name'] ?? 'All']);
            fputcsv($out, ['Opening Qty', $header['opening_qty'], 'Opening Value', $header['opening_value']]);
            fputcsv($out, ['Closing Qty', $header['closing_qty'], 'Closing Value', $header['closing_value']]);
            fputcsv($out, ['Generated By', $header['generated_by'], 'Generated Time', $header['generated_at']]);
            fputcsv($out, []);
            fputcsv($out, [
                'Item Description', 'Unit',
                'Opening Qty', 'Opening Value',
                'Purchase Qty', 'Purchase Value',
                'Sales Qty', 'Sales Value',
                'Closing Qty', 'Closing Value',
            ]);

            foreach ($data['rows'] as $row) {
                fputcsv($out, [
                    $row['product_name'], $row['unit'],
                    $row['opening_qty'], $row['opening_value'],
                    $row['purchase_qty'], $row['purchase_value'],
                    $row['sales_qty'], $row['sales_value'],
                    $row['closing_qty'], $row['closing_value'],
                ]);
            }

            $summary = $data['summary'];
            fputcsv($out, [
                'Total', '',
                '', $summary['opening_value'],
                '', $summary['purchase_value'],
                '', $summary['sales_value'],
                '', $summary['closing_value'],
            ]);

            fclose($out);
        }, $this->filename('csv'), [
            'Content-Type' => 'text/csv; charset=UTF-8',
        ]);
    }

    /** @return array<string, mixed> */
    private function validated(Request $request): array
    {
        $request->validate([
            'location_id' => ['nullable', 'integer', 'exists:inv_locations,id'],
            'store_id'    => ['nullable', 'integer', 'exists:inv_stores,id'],
            'category_id' => ['nullable', 'integer', 'exists:inv_categories,id'],
            'date_from'   => ['nullable', 'date'],
            'date_to'     => ['nullable', 'date', 'after_or_equal:date_from'],
        ]);

        return $request->only(['location_id', 'store_id', 'category_id', 'date_from', 'date_to']);
    }

    private function filename(string $extension): string
    {
        return 'StockMovementSummary_' . now()->format('Ymd') . '.' . $extension;
    }
}
