<?php

declare(strict_types=1);

namespace Modules\Inventory\Http\Controllers;

use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Symfony\Component\HttpFoundation\StreamedResponse;
use Modules\Inventory\Services\SupplierWiseGrnDetailsService;

class SupplierWiseGrnDetailsExportController extends Controller
{
    public function __construct(private readonly SupplierWiseGrnDetailsService $service)
    {
        $this->middleware('permission:view_reports');
    }

    public function pdf(Request $request): Response
    {
        $data = $this->service->build($this->validated($request));

        $pdf = Pdf::loadView('inventory::pdf.supplier_wise_grn_details', $data)
            ->setPaper('a4', 'landscape')
            ->setOptions([
                'defaultFont'          => 'DejaVu Sans',
                'isHtml5ParserEnabled' => true,
                'isPhpEnabled'         => false,
                'dpi'                  => 150,
                'defaultPaperSize'     => 'a4',
            ]);

        return $pdf->download($this->filename('pdf'));
    }

    public function csv(Request $request): StreamedResponse
    {
        $data = $this->service->build($this->validated($request));

        return response()->streamDownload(function () use ($data): void {
            $out    = fopen('php://output', 'w');
            $header = $data['header'];

            fputcsv($out, ['Supplier Wise GRN Details']);
            fputcsv($out, [$header['company_name'], $header['company_address'], $header['company_email']]);
            fputcsv($out, []);
            fputcsv($out, ['Period', $header['date_from'] . ' - ' . $header['date_to'], 'Supplier', $header['supplier_name'] ?? 'All']);
            fputcsv($out, ['Item', $header['product_name'] ?? 'All']);
            fputcsv($out, ['Generated By', $header['generated_by'], 'Generated Time', $header['generated_at']]);
            fputcsv($out, []);
            fputcsv($out, ['Supplier', 'GRN No', 'GRN Date', 'PO No', 'Item Code', 'Item Name', 'Qty', 'UOM', 'Unit Price', 'Discount %', 'Tax %', 'Amount']);

            foreach ($data['suppliers'] as $supplier) {
                foreach ($supplier['grns'] as $grn) {
                    foreach ($grn['items'] as $item) {
                        fputcsv($out, [
                            $supplier['supplier_name'],
                            $grn['grn_no'],
                            $grn['grn_date'],
                            $grn['po_no'] ?? '-',
                            $item['product_code'],
                            $item['item_name'],
                            $item['quantity'],
                            $item['unit'] ?? '-',
                            $item['unit_price'],
                            $item['discount'],
                            $item['tax'],
                            $item['amount'],
                        ]);
                    }
                    fputcsv($out, ['', $grn['grn_no'], '', '', '', 'TOTAL', '', '', '', '', '', $grn['grn_amount']]);
                }
                fputcsv($out, ['', '', '', '', '', 'Total ' . $supplier['supplier_name'], '', '', '', '', '', $supplier['supplier_amount']]);
                fputcsv($out, []);
            }

            $summary = $data['summary'];
            fputcsv($out, ['', '', '', '', '', 'Grand Total', '', '', '', '', '', $summary['total_amount']]);

            fclose($out);
        }, $this->filename('csv'), [
            'Content-Type' => 'text/csv; charset=UTF-8',
        ]);
    }

    /** @return array<string, mixed> */
    private function validated(Request $request): array
    {
        $request->validate([
            'date_from'   => ['required', 'date'],
            'date_to'     => ['required', 'date', 'after_or_equal:date_from'],
            'supplier_id' => ['nullable', 'integer', 'exists:inv_supplier_masters,id'],
            'product_id'  => ['nullable', 'integer', 'exists:inv_products,id'],
        ]);

        return $request->only(['date_from', 'date_to', 'supplier_id', 'product_id']);
    }

    private function filename(string $extension): string
    {
        return 'SupplierWiseGrnDetails_' . now()->format('Ymd') . '.' . $extension;
    }
}
